// apps/web/src/features/events/event-detail.tsx
'use client';
'use no memo';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocale, useTranslations } from 'next-intl';
import { lazy, Suspense, useState } from 'react';
import { AppLink } from '@/components/app-link';
import { LazyBoundary } from '@/components/lazy-boundary';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { BookStores } from '@/features/club-detail/sidebar';
import { useSession } from '@/features/clubs/use-session';
import { api } from '@/lib/api';
import { formatDate } from '@/lib/format';
import { RsvpButton } from './rsvp-button';
import { useEvent, useRsvp } from './use-events';

// the Maps loader and its key request only matter on events that have coordinates
const EventMap = lazy(() => import('./event-map'));

const CARD = 'rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6';
const SECTION_TITLE = 'text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3';
const BACK_LINK = 'inline-flex items-center gap-1.5 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors';

function BookDetails({ bookId }: { bookId: string }) {
  const t = useTranslations('EVENTS');
  const query = useQuery({ queryKey: ['book', bookId], queryFn: () => api.books.details(bookId), retry: false, refetchOnWindowFocus: false });
  const book = query.data;
  return (
    <div className="rounded-xl border border-[var(--color-sepia)] bg-[var(--color-surface)] p-5 space-y-4">
      {query.isPending ? (
        <div className="flex justify-center py-4">
          <Spinner />
        </div>
      ) : (
        book && (
          <>
            <div className="flex gap-4">
              {book.thumbnail && (
                // eslint-disable-next-line @next/next/no-img-element -- cover URLs are arbitrary hosts
                <img src={book.thumbnail} alt={book.title} width={64} height={96} referrerPolicy="no-referrer" className="w-16 h-24 object-cover rounded-lg shadow-sm shrink-0" />
              )}
              <div>
                <p className="font-display font-bold text-lg text-[var(--color-ink)] leading-tight">{book.title}</p>
                <p className="text-sm text-[var(--color-ink-muted)] mt-0.5">{book.authors.join(', ')}</p>
                {book.publishedDate && (
                  <p className="text-xs text-[var(--color-ink-muted)] mt-0.5 opacity-70">
                    {t('book_published')}: {book.publishedDate.slice(0, 4)}
                  </p>
                )}
              </div>
            </div>
            {book.description && (
              <div>
                <p className="font-fantasy text-xs uppercase tracking-widest text-[var(--color-primary-500)] mb-2">📖 {t('book_about')}</p>
                <p className="text-sm text-[var(--color-ink)] leading-relaxed">{book.description}</p>
              </div>
            )}
            {book.authors.length > 0 && (
              <div>
                <p className="font-fantasy text-xs uppercase tracking-widest text-[var(--color-primary-500)] mb-2">✍️ {t('book_author')}</p>
                <p className="text-sm font-medium text-[var(--color-ink)]">{book.authors.join(', ')}</p>
                {book.publisher && <p className="text-xs text-[var(--color-ink-muted)] mt-0.5">{book.publisher}</p>}
              </div>
            )}
          </>
        )
      )}
    </div>
  );
}

export function EventDetail({ id }: { id: string }) {
  const t = useTranslations('EVENTS');
  const tNew = useTranslations('CREATE_EVENT');
  const locale = useLocale();
  const queryClient = useQueryClient();
  const { user } = useSession();
  const query = useEvent(id);
  const { rsvp, pendingIds } = useRsvp();
  const [bookOpen, setBookOpen] = useState(false);
  const [confirmCancel, setConfirmCancel] = useState(false);

  const cancelEvent = useMutation({
    mutationFn: () => api.events.cancel(id),
    onSettled: () => queryClient.invalidateQueries({ queryKey: ['events'] }),
  });

  if (query.isPending) {
    return (
      <section className="max-w-3xl mx-auto px-4 py-8" aria-busy="true">
        <div className="animate-pulse space-y-4">
          <div className="h-8 w-64 bg-gray-200 dark:bg-gray-700 rounded-lg" />
          <div className="h-4 w-full bg-gray-200 dark:bg-gray-700 rounded-lg" />
        </div>
      </section>
    );
  }

  const event = query.data;
  if (!event) {
    return (
      <section className="max-w-3xl mx-auto px-4 py-8 text-center" role="alert">
        <p className="text-6xl mb-4" aria-hidden="true">😕</p>
        <p className="text-gray-500 dark:text-gray-400 mb-6">{t('load_error')}</p>
        <AppLink href="/events" className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-primary-700 transition-colors">
          {t('back_to_events')}
        </AppLink>
      </section>
    );
  }

  const isOrganizer = user !== null && event.organizerId === user.id;
  const actioning = pendingIds.includes(event.id) || cancelEvent.isPending;
  const venue = event.afterMeetingVenue;

  return (
    <section className="max-w-3xl mx-auto px-4 py-8 space-y-6">
      <nav>
        <AppLink href="/events" className={BACK_LINK}>
          {t('back_to_events')}
        </AppLink>
      </nav>

      <div className={`${CARD} space-y-3`}>
        <div className="flex items-start justify-between gap-4">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">{event.title}</h1>
          {event.status !== 'scheduled' && (
            <span
              className={`text-xs rounded-full px-2.5 py-1 shrink-0 ${
                event.status === 'cancelled' ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400' : 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'
              }`}
            >
              {event.status}
            </span>
          )}
        </div>

        <AppLink href={`/clubs/${event.clubId}`} className="text-sm text-primary-600 dark:text-primary-400 hover:underline">
          <span aria-hidden="true">📚</span> {event.clubName}
        </AppLink>

        <div className="flex flex-wrap gap-4 text-sm text-gray-600 dark:text-gray-400">
          <span>
            <span aria-hidden="true">📅</span> {formatDate(event.date, locale)}
          </span>
          {event.city && (
            <span>
              <span aria-hidden="true">📍</span> {event.address || event.city}
            </span>
          )}
          {event.durationMinutes ? (
            <span>
              <span aria-hidden="true">⏱</span> {event.durationMinutes} {t('minutes_abbr')}
            </span>
          ) : null}
          <span>
            <span aria-hidden="true">👤</span> {event.attendeeCount} {t('attending')}
          </span>
        </div>

        {user && event.status !== 'cancelled' && (
          <div className="flex gap-3 pt-2">
            <RsvpButton
              attending={event.isAttending}
              loading={actioning}
              showCancel
              size="default"
              onClick={() => rsvp({ eventId: event.id, attending: !event.isAttending })}
            />
          </div>
        )}

        {(event.coverUrl || event.bookTitle) && (
          <div className="flex gap-4 items-start pt-1 border-t border-gray-100 dark:border-gray-700">
            {event.coverUrl && (
              // eslint-disable-next-line @next/next/no-img-element -- cover URLs are arbitrary hosts
              <img
                src={event.coverUrl}
                alt={event.bookTitle ?? 'Book cover'}
                width={64}
                height={96}
                referrerPolicy="no-referrer"
                loading="lazy"
                className="w-16 h-24 object-cover rounded-lg shadow-[var(--shadow-parchment-lg)] shrink-0 border border-[var(--color-sepia)]"
              />
            )}
            <div className="flex-1 min-w-0 pt-1">
              {event.bookTitle && <p className="font-display font-semibold text-[var(--color-ink)] leading-snug text-sm">📖 {event.bookTitle}</p>}
              {event.googleBookId && (
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  aria-expanded={bookOpen}
                  className="mt-1 h-auto px-0 py-0 text-xs text-[var(--color-primary-600)] dark:text-[var(--color-primary-400)] hover:bg-transparent hover:underline font-medium"
                  onClick={() => setBookOpen((open) => !open)}
                >
                  {bookOpen ? t('book_details_hide') : t('book_details_btn')}
                </Button>
              )}
            </div>
          </div>
        )}
        {bookOpen && event.googleBookId && <BookDetails bookId={event.googleBookId} />}
      </div>

      {isOrganizer && event.status !== 'cancelled' && (
        <section className="rounded-2xl border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-900/20 p-6">
          <h2 className="text-sm font-semibold text-yellow-800 dark:text-yellow-300 uppercase tracking-wide mb-3">{t('organizer_controls')}</h2>
          <div className="flex gap-3">
            <AppLink href={`/events/${event.id}/edit`} className="rounded-lg bg-primary-600 hover:bg-primary-700 px-3 py-1.5 text-xs font-semibold text-white transition-colors">
              {t('editEvent')}
            </AppLink>
            <button
              type="button"
              disabled={actioning}
              onClick={() => setConfirmCancel(true)}
              className="rounded-lg bg-red-600 hover:bg-red-700 px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60 transition-colors"
            >
              {t('cancel_event')}
            </button>
          </div>
          {confirmCancel && (
            <div className="flex items-center justify-between gap-3 mt-3 px-3 py-2 rounded-lg bg-red-100 dark:bg-red-900/30">
              <span className="text-xs text-red-700 dark:text-red-300">{t('cancel_confirm')}</span>
              <div className="flex gap-2 flex-shrink-0">
                <button
                  type="button"
                  disabled={actioning}
                  onClick={() => {
                    setConfirmCancel(false);
                    cancelEvent.mutate();
                  }}
                  className="rounded-lg bg-red-600 hover:bg-red-700 px-3 py-1 text-xs font-semibold text-white disabled:opacity-60 transition-colors"
                >
                  {t('cancel_event')}
                </button>
                <button type="button" onClick={() => setConfirmCancel(false)} className="rounded-lg bg-white dark:bg-gray-700 px-3 py-1 text-xs font-semibold text-gray-700 dark:text-gray-200 transition-colors">
                  {tNew('cancel')}
                </button>
              </div>
            </div>
          )}
        </section>
      )}

      {event.bookTitle && (
        <section className={CARD}>
          <BookStores bookTitle={event.bookTitle} />
        </section>
      )}

      {event.description && (
        <section className={CARD}>
          <h2 className={SECTION_TITLE}>{t('about')}</h2>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{event.description}</p>
        </section>
      )}

      {(event.theme || event.tags.length > 0) && (
        <section className={CARD}>
          <h2 className={SECTION_TITLE}>{t('tags')}</h2>
          <div className="flex flex-wrap gap-2">
            {event.theme && <span className="rounded-full bg-accent-100 dark:bg-accent-900/30 px-3 py-1 text-xs font-medium text-accent-700 dark:text-accent-300">{event.theme}</span>}
            {event.tags.map((tag) => (
              <span key={tag} className="rounded-full bg-gray-100 dark:bg-gray-700 px-3 py-1 text-xs text-gray-600 dark:text-gray-400">
                {tag}
              </span>
            ))}
          </div>
        </section>
      )}

      {venue && (
        <section className={CARD}>
          <h2 className={SECTION_TITLE}>{t('after_meeting_venue')}</h2>
          <p className="font-medium text-gray-900 dark:text-white">{venue.name}</p>
          <p className="text-sm text-gray-500 dark:text-gray-400">{venue.address}</p>
          {venue.description && <p className="text-sm text-gray-600 dark:text-gray-300 mt-2">{venue.description}</p>}
        </section>
      )}

      {event.lat != null && event.lng != null && (
        <LazyBoundary fallback={null}>
          <Suspense fallback={null}>
            <EventMap lat={event.lat} lng={event.lng} address={event.address} afterMeetingVenue={venue} />
          </Suspense>
        </LazyBoundary>
      )}
    </section>
  );
}

// src/app/features/events/event-detail/event-detail.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  computed,
  input,
} from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { RouterLink } from '@angular/router';
import { TranslateModule } from '@ngx-translate/core';
import { rxResource } from '@angular/core/rxjs-interop';
import { map, catchError, of } from 'rxjs';
import { EventService } from '../../../core/services/event.service';
import { AuthService } from '../../../core/auth/auth.service';
import { ApiEvent, mapEvent } from '../../../core/api/api-mappers';
import { FormatDatePipe } from '../../../shared/pipes/format-date.pipe';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-event-detail',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, TranslateModule, FormatDatePipe],
  templateUrl: './event-detail.component.html',
})
export class EventDetailComponent {
  readonly id = input.required<string>();

  private readonly http = inject(HttpClient);
  private readonly eventService = inject(EventService);
  readonly auth = inject(AuthService);

  private readonly _eventResource = rxResource({
    params: () => this.id(),
    loader: ({ params: id }) =>
      this.http.get<ApiEvent>(`${environment.apiUrl}/events/${id}`).pipe(
        map(mapEvent),
        catchError(() => of(null)),
      ),
  });

  readonly event = computed(() => this._eventResource.value() ?? null);
  readonly isLoading = this._eventResource.isLoading;
  readonly errorMessage = computed(() =>
    !this._eventResource.isLoading() && this._eventResource.error() ? 'EVENT.LOAD_ERROR' : null,
  );
  readonly isActioning = signal(false);

  readonly isOrganizer = computed(
    () => !!this.auth.currentUser() && this.event()?.organizerId === this.auth.currentUser()?.id,
  );

  async onAttend(): Promise<void> {
    this.isActioning.set(true);
    try {
      await this.eventService.attendEvent(this.id());
      this._eventResource.reload();
    } finally {
      this.isActioning.set(false);
    }
  }

  async onCancelAttend(): Promise<void> {
    this.isActioning.set(true);
    try {
      await this.eventService.cancelAttendance(this.id());
      this._eventResource.reload();
    } finally {
      this.isActioning.set(false);
    }
  }

  async onCancelEvent(): Promise<void> {
    if (!confirm('Cancel this event?')) return;
    this.isActioning.set(true);
    try {
      await this.eventService.cancelEvent(this.id());
      this._eventResource.reload();
    } finally {
      this.isActioning.set(false);
    }
  }
}

@if (isLoading()) {
  <section class="max-w-3xl mx-auto px-4 py-8" aria-busy="true">
    <div class="animate-pulse space-y-4">
      <div class="h-8 w-64 bg-gray-200 dark:bg-gray-700 rounded-lg"></div>
      <div class="h-4 w-full bg-gray-200 dark:bg-gray-700 rounded-lg"></div>
    </div>
  </section>
} @else if (errorMessage()) {
  <section class="max-w-3xl mx-auto px-4 py-8 text-center" role="alert">
    <p class="text-6xl mb-4" aria-hidden="true">😕</p>
    <p class="text-gray-500 dark:text-gray-400 mb-6">{{ errorMessage() }}</p>
    <a routerLink="/events"
       class="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-primary-700 transition-colors">
      {{ 'EVENTS.back_to_events' | translate }}
    </a>
  </section>
} @else if (event()) {
  <section class="max-w-3xl mx-auto px-4 py-8 space-y-6">

    <!-- Back navigation -->
    <nav>
      <a routerLink="/events"
         class="inline-flex items-center gap-1.5 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors">
        {{ 'EVENTS.back_to_events' | translate }}
      </a>
    </nav>

    <!-- Header -->
    <div class="rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6 space-y-3">
      <div class="flex items-start justify-between gap-4">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">{{ event()!.title }}</h1>
        @if (event()!.status !== 'scheduled') {
          <span class="text-xs rounded-full px-2.5 py-1 shrink-0"
                [class]="event()!.status === 'cancelled'
                  ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                  : 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400'">
            {{ event()!.status }}
          </span>
        }
      </div>

      <a [routerLink]="['/clubs', event()!.clubId]"
         class="text-sm text-primary-600 dark:text-primary-400 hover:underline">
        📚 {{ event()!.clubName }}
      </a>

      <div class="flex flex-wrap gap-4 text-sm text-gray-600 dark:text-gray-400">
        <span>📅 {{ event()!.date | formatDate }}</span>
        @if (event()!.city) {
          <span>📍 {{ event()!.address || event()!.city }}</span>
        }
        @if (event()!.durationMinutes) {
          <span>⏱ {{ event()!.durationMinutes }} {{ 'EVENTS.minutes_abbr' | translate }}</span>
        }
        <span>👤 {{ event()!.attendeeCount }} {{ 'EVENTS.attending' | translate }}</span>
      </div>

      <!-- RSVP actions -->
      @if (auth.isAuthenticated() && event()!.status !== 'cancelled') {
        <div class="flex gap-3 pt-2">
          <app-event-rsvp-button
            [attending]="!!event()!.isAttending"
            [loading]="isActioning()"
            [showCancel]="true"
            size="default"
            (clicked)="event()!.isAttending ? onCancelAttend() : onAttend()"
          />
          @if (event()?.isAttending || isOrganizer()) {
            @if (eventRoom()) {
              <button hlmBtn variant="outline" (click)="openEventChat()">{{ 'EVENT.event_chat_btn' | translate }}</button>
            } @else if (isOrganizer()) {
              <button hlmBtn variant="outline" (click)="openEventChat()">{{ 'EVENT.event_chat_start_btn' | translate }}</button>
            }
          }
        </div>
      }

      <!-- Book cover + info -->
      @if (event()!.coverUrl || event()!.bookTitle) {
        <div class="flex gap-4 items-start pt-1 border-t border-gray-100 dark:border-gray-700">
          @if (event()!.coverUrl) {
            <img [src]="event()!.coverUrl" [alt]="event()!.bookTitle ?? 'Book cover'"
                 class="w-16 h-24 object-cover rounded-lg shadow-[var(--shadow-parchment-lg)] shrink-0 border border-[var(--color-sepia)]"
                 loading="lazy" />
          }
          <div class="flex-1 min-w-0 pt-1">
            @if (event()!.bookTitle) {
              <p class="font-display font-semibold text-[var(--color-ink)] leading-snug text-sm">📖 {{ event()!.bookTitle }}</p>
            }
            @if (event()!.googleBookId) {
              <button hlmBtn variant="ghost" size="sm"
                      class="mt-1 h-auto px-0 py-0 text-xs text-[var(--color-primary-600)] dark:text-[var(--color-primary-400)] hover:bg-transparent hover:underline font-medium"
                      (click)="openBookDetails()">
                {{ bookDetailsOpen() ? ('EVENTS.book_details_hide' | translate) : ('EVENTS.book_details_btn' | translate) }}
              </button>
            }
          </div>
        </div>
      }
      @if (bookDetailsOpen()) {
        <div class="rounded-xl border border-[var(--color-sepia)] bg-[var(--color-surface)] p-5 space-y-4 animate-[slideUp_0.3s_ease-out_both]">
          @if (isLoadingBookDetails()) {
            <div class="flex justify-center py-4"><hlm-spinner /></div>
          } @else if (bookDetails()) {
            <div class="flex gap-4">
              @if (bookDetails()!.thumbnail) {
                <img [src]="bookDetails()!.thumbnail" [alt]="bookDetails()!.title" class="w-16 h-24 object-cover rounded-lg shadow-sm shrink-0" />
              }
              <div>
                <p class="font-display font-bold text-lg text-[var(--color-ink)] leading-tight">{{ bookDetails()!.title }}</p>
                <p class="text-sm text-[var(--color-ink-muted)] mt-0.5">{{ bookDetails()!.authors.join(', ') }}</p>
                @if (bookDetails()!.publishedDate) {
                  <p class="text-xs text-[var(--color-ink-muted)] mt-0.5 opacity-70">{{ 'EVENTS.book_published' | translate }}: {{ bookDetails()!.publishedDate | slice:0:4 }}</p>
                }
              </div>
            </div>
            @if (bookDetails()!.description) {
              <div>
                <p class="font-fantasy text-xs uppercase tracking-widest text-[var(--color-primary-500)] mb-2">📖 {{ 'EVENTS.book_about' | translate }}</p>
                <p class="text-sm text-[var(--color-ink)] leading-relaxed">{{ bookDetails()!.description }}</p>
              </div>
            }
            @if (bookDetails()!.authors.length > 0) {
              <div>
                <p class="font-fantasy text-xs uppercase tracking-widest text-[var(--color-primary-500)] mb-2">✍️ {{ 'EVENTS.book_author' | translate }}</p>
                <p class="text-sm font-medium text-[var(--color-ink)]">{{ bookDetails()!.authors.join(', ') }}</p>
                @if (bookDetails()!.publisher) {
                  <p class="text-xs text-[var(--color-ink-muted)] mt-0.5">{{ bookDetails()!.publisher }}</p>
                }
              </div>
            }
          }
        </div>
      }
    </div>

    <!-- Organizer actions -->
    @if (isOrganizer() && event()!.status !== 'cancelled') {
      <section class="rounded-2xl border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-900/20 p-6">
        <h2 class="text-sm font-semibold text-yellow-800 dark:text-yellow-300 uppercase tracking-wide mb-3">{{ 'EVENTS.organizer_controls' | translate }}</h2>
        <div class="flex gap-3">
          <a [routerLink]="['edit']"
             class="rounded-lg bg-primary-600 hover:bg-primary-700 px-3 py-1.5 text-xs font-semibold text-white transition-colors">
            {{ 'EVENTS.editEvent' | translate }}
          </a>
          <button type="button"
                  [disabled]="isActioning()"
                  (click)="onCancelEvent()"
                  class="rounded-lg bg-red-600 hover:bg-red-700 px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60 transition-colors">
            {{ 'EVENTS.cancel_event' | translate }}
          </button>
        </div>
      </section>
    }

    <!-- Book stores availability -->
    @if (event()?.bookTitle) {
      <section class="rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6">
        <app-book-stores [bookTitle]="event()!.bookTitle!" />
      </section>
    }

    <!-- Description -->
    @if (event()!.description) {
      <section class="rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3">{{ 'EVENTS.about' | translate }}</h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">{{ event()!.description }}</p>
      </section>
    }

    <!-- Theme + Tags -->
    @if (event()!.theme || event()!.tags.length > 0) {
      <section class="rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3">{{ 'EVENTS.tags' | translate }}</h2>
        <div class="flex flex-wrap gap-2">
          @if (event()!.theme) {
            <span class="rounded-full bg-accent-100 dark:bg-accent-900/30 px-3 py-1 text-xs font-medium text-accent-700 dark:text-accent-300">
              {{ event()!.theme }}
            </span>
          }
          @for (tag of event()!.tags; track tag) {
            <span class="rounded-full bg-gray-100 dark:bg-gray-700 px-3 py-1 text-xs text-gray-600 dark:text-gray-400">
              {{ tag }}
            </span>
          }
        </div>
      </section>
    }

    <!-- After-meeting venue -->
    @if (event()!.afterMeetingVenue) {
      <section class="rounded-2xl bg-white dark:bg-gray-800 shadow-sm p-6">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3">{{ 'EVENTS.after_meeting_venue' | translate }}</h2>
        <p class="font-medium text-gray-900 dark:text-white">{{ event()!.afterMeetingVenue!.name }}</p>
        <p class="text-sm text-gray-500 dark:text-gray-400">{{ event()!.afterMeetingVenue!.address }}</p>
        @if (event()!.afterMeetingVenue!.description) {
          <p class="text-sm text-gray-600 dark:text-gray-300 mt-2">{{ event()!.afterMeetingVenue!.description }}</p>
        }
      </section>
    }

    <app-event-map
      [lat]="event()!.lat"
      [lng]="event()!.lng"
      [address]="event()!.address"
      [afterMeetingVenue]="event()!.afterMeetingVenue"
    />

  </section>
}
