// src/app/features/support/support-board/support-board.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { AuthService } from '../../../core/auth/auth.service';
import { SupportService } from '../../../core/services/support.service';
import { SeoService } from '../../../core/services/seo.service';
import { Submission, SubmissionStatus } from '../../../core/models/support.model';
import { SubmissionCardComponent } from '../submission-card/submission-card.component';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { HlmSpinner } from '../../../shared/spartan/spinner/src';

type KanbanStatus = Extract<SubmissionStatus, 'pending' | 'approved' | 'in_progress' | 'done' | 'rejected'>;

@Component({
  selector: 'app-support-board',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, TranslatePipe, SubmissionCardComponent, EmptyStateComponent, HlmSpinner],
  templateUrl: './support-board.component.html',
})
export class SupportBoardComponent implements OnInit {
  protected readonly support = inject(SupportService);
  protected readonly auth = inject(AuthService);
  private readonly seo = inject(SeoService);

  readonly columns: KanbanStatus[] = ['pending', 'approved', 'in_progress', 'done', 'rejected'];

  readonly complaints = computed<Submission[]>(() =>
    this.support.submissions().filter(s => s.type === 'complaint'),
  );

  readonly comments = computed<Submission[]>(() =>
    this.support.submissions().filter(s => s.type === 'comment'),
  );

  readonly suggestions = computed<Submission[]>(() =>
    this.support.submissions().filter(s => s.type === 'suggestion'),
  );

  readonly suggestionsByStatus = computed<Record<KanbanStatus, Submission[]>>(() => {
    const groups: Record<KanbanStatus, Submission[]> = {
      pending: [], approved: [], in_progress: [], done: [], rejected: [],
    };
    for (const s of this.suggestions()) {
      if (s.status in groups) groups[s.status as KanbanStatus].push(s);
    }
    return groups;
  });

  constructor() {
    this.seo.setPageI18n('SUPPORT.title');
  }

  async ngOnInit(): Promise<void> {
    await this.support.loadSubmissions();
  }

  async onApprove(s: Submission): Promise<void> {
    await this.runStatus(s, 'approved');
  }

  async onReject(s: Submission): Promise<void> {
    await this.runStatus(s, 'rejected');
  }

  async onAdvance(s: Submission): Promise<void> {
    let next: 'in_progress' | 'done' | null = null;
    if (s.status === 'approved') next = 'in_progress';
    else if (s.status === 'in_progress') next = 'done';
    if (next) await this.runStatus(s, next);
  }

  private async runStatus(s: Submission, status: 'approved' | 'rejected' | 'in_progress' | 'done'): Promise<void> {
    try {
      await this.support.updateStatus(s.id, status);
    } catch {
      // interceptor surfaces the error toast
    }
  }
}

<div class="page-max-w px-4 sm:px-6 py-6 space-y-8">

  <!-- ── Header ── -->
  <header class="flex items-center justify-between flex-wrap gap-4">
    <div>
      <h1 class="font-display text-3xl font-bold text-gray-900 dark:text-white">💬 {{ 'SUPPORT.title' | translate }}</h1>
      <p class="text-gray-500 dark:text-gray-400 mt-1 text-sm">{{ 'SUPPORT.subtitle' | translate }}</p>
    </div>
    <a
      routerLink="/support/new"
      data-testid="support-new"
      class="rounded-lg bg-gradient-brand px-4 py-2 text-sm font-medium text-white transition-all hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
    >
      {{ 'SUPPORT.new_btn' | translate }}
    </a>
  </header>

  @if (support.isLoading()) {
    <div class="flex justify-center py-16"><hlm-spinner /></div>
  } @else {

    <!-- ── Complaints ── -->
    <section class="space-y-4">
      <h2 class="text-lg font-semibold text-[var(--color-ink)]">{{ 'SUPPORT.complaints_heading' | translate }}</h2>
      @if (complaints().length === 0) {
        <app-empty-state
          icon="😠"
          [title]="'SUPPORT.empty_complaints_title' | translate"
          [description]="'SUPPORT.empty_complaints_desc' | translate"
        />
      } @else {
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          @for (item of complaints(); track item.id) {
            <app-submission-card [submission]="item" />
          }
        </div>
      }
    </section>

    <!-- ── Comments ── -->
    <section class="space-y-4">
      <h2 class="text-lg font-semibold text-[var(--color-ink)]">{{ 'SUPPORT.comments_heading' | translate }}</h2>
      @if (comments().length === 0) {
        <app-empty-state
          icon="💬"
          [title]="'SUPPORT.empty_comments_title' | translate"
          [description]="'SUPPORT.empty_comments_desc' | translate"
        />
      } @else {
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          @for (item of comments(); track item.id) {
            <app-submission-card [submission]="item" />
          }
        </div>
      }
    </section>

    <!-- ── Suggestions Kanban ── -->
    <section class="space-y-4">
      <h2 class="text-lg font-semibold text-[var(--color-ink)]">{{ 'SUPPORT.suggestions_heading' | translate }}</h2>
      @if (suggestions().length === 0) {
        <app-empty-state
          icon="💡"
          [title]="'SUPPORT.empty_suggestions_title' | translate"
          [description]="'SUPPORT.empty_suggestions_desc' | translate"
        />
      } @else {
        <div class="overflow-x-auto pb-2 -mx-4 px-4">
          <div class="flex gap-4 md:grid md:grid-cols-5 md:gap-4">
            @for (status of columns; track status) {
              <div class="flex w-72 shrink-0 flex-col gap-3 md:w-auto">
                <div class="flex items-center justify-between rounded-lg bg-[var(--color-surface-raised)] px-3 py-2">
                  <span class="text-sm font-semibold text-[var(--color-ink)]">{{ 'SUPPORT.status_' + status | translate }}</span>
                  <span class="text-xs text-[var(--color-ink-muted)]">{{ suggestionsByStatus()[status].length }}</span>
                </div>
                <div class="flex flex-col gap-3">
                  @for (item of suggestionsByStatus()[status]; track item.id) {
                    <app-submission-card
                      [submission]="item"
                      [isAdmin]="auth.isAdmin()"
                      (approve)="onApprove($event)"
                      (reject)="onReject($event)"
                      (advance)="onAdvance($event)"
                    />
                  } @empty {
                    <p class="px-1 text-xs text-[var(--color-ink-muted)]">{{ 'SUPPORT.column_empty' | translate }}</p>
                  }
                </div>
              </div>
            }
          </div>
        </div>
      }
    </section>

  }
</div>

// apps/web/src/features/support/support-board.tsx
'use client';
'use no memo';

import type { Submission, SubmissionStatus } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import type { ReactNode } from 'react';
import { AppLink } from '@/components/app-link';
import { EmptyState } from '@/components/empty-state';
import { Spinner } from '@/components/ui/spinner';
import { useSession } from '@/features/clubs/use-session';
import { SubmissionCard } from './submission-card';
import { useSubmissions, useUpdateStatus } from './use-support';

const COLUMNS = ['pending', 'approved', 'in_progress', 'done', 'rejected'] as const satisfies readonly SubmissionStatus[];
const GRID = 'grid gap-4 sm:grid-cols-2 lg:grid-cols-3';
const NO_ITEMS: Submission[] = [];

function Section({ heading, children }: { heading: string; children: ReactNode }) {
  return (
    <section className="space-y-4">
      <h2 className="text-lg font-semibold text-[var(--color-ink)]">{heading}</h2>
      {children}
    </section>
  );
}

export function SupportBoard() {
  const t = useTranslations('SUPPORT');
  const { user } = useSession();
  const query = useSubmissions();
  const updateStatus = useUpdateStatus();
  const items = query.data ?? NO_ITEMS;
  const isAdmin = user?.role === 'admin';

  const complaints = items.filter((s) => s.type === 'complaint');
  const comments = items.filter((s) => s.type === 'comment');
  const suggestions = items.filter((s) => s.type === 'suggestion');

  // a failed status change is swallowed: the client already toasts 5xx and timeouts
  const move = (s: Submission, status: 'approved' | 'rejected' | 'in_progress' | 'done') => updateStatus.mutate({ id: s.id, status });
  const advance = (s: Submission) => {
    if (s.status === 'approved') move(s, 'in_progress');
    else if (s.status === 'in_progress') move(s, 'done');
  };

  const list = (group: Submission[], icon: string, key: 'complaints' | 'comments') =>
    group.length === 0 ? (
      <EmptyState icon={icon} title={t(`empty_${key}_title`)} description={t(`empty_${key}_desc`)} />
    ) : (
      <div className={GRID}>
        {group.map((item) => (
          <SubmissionCard key={item.id} submission={item} />
        ))}
      </div>
    );

  return (
    <div className="page-max-w px-4 sm:px-6 py-6 space-y-8">
      <header className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-display text-3xl font-bold text-gray-900 dark:text-white">💬 {t('title')}</h1>
          <p className="text-gray-500 dark:text-gray-400 mt-1 text-sm">{t('subtitle')}</p>
        </div>
        <AppLink
          href="/support/new"
          data-testid="support-new"
          className="rounded-lg bg-gradient-brand px-4 py-2 text-sm font-medium text-white transition-all hover:opacity-90 outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-primary-500)] focus-visible:ring-offset-2"
        >
          {t('new_btn')}
        </AppLink>
      </header>

      {query.isPending ? (
        <div className="flex justify-center py-16">
          <Spinner aria-label={t('loading')} />
        </div>
      ) : (
        <>
          <Section heading={t('complaints_heading')}>{list(complaints, '😠', 'complaints')}</Section>
          <Section heading={t('comments_heading')}>{list(comments, '💬', 'comments')}</Section>
          <Section heading={t('suggestions_heading')}>
            {suggestions.length === 0 ? (
              <EmptyState icon="💡" title={t('empty_suggestions_title')} description={t('empty_suggestions_desc')} />
            ) : (
              <div className="overflow-x-auto pb-2 -mx-4 px-4">
                <div className="flex gap-4 md:grid md:grid-cols-5 md:gap-4">
                  {COLUMNS.map((status) => {
                    const column = suggestions.filter((s) => s.status === status);
                    return (
                      <div key={status} className="flex w-72 shrink-0 flex-col gap-3 md:w-auto">
                        <div className="flex items-center justify-between rounded-lg bg-[var(--color-surface-raised)] px-3 py-2">
                          <span className="text-sm font-semibold text-[var(--color-ink)]">{t(`status_${status}`)}</span>
                          <span className="text-xs text-[var(--color-ink-muted)]">{column.length}</span>
                        </div>
                        <div className="flex flex-col gap-3">
                          {column.map((item) => (
                            <SubmissionCard key={item.id} submission={item} isAdmin={isAdmin} onApprove={(s) => move(s, 'approved')} onReject={(s) => move(s, 'rejected')} onAdvance={advance} />
                          ))}
                          {column.length === 0 && <p className="px-1 text-xs text-[var(--color-ink-muted)]">{t('column_empty')}</p>}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </Section>
        </>
      )}
    </div>
  );
}
