// apps/web/src/features/organizer/edit-club.tsx
'use client';
'use no memo';

import { zodResolver } from '@hookform/resolvers/zod';
import { editClubForm, isClubStub, splitTags, type Club, type EditClubForm } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import { useForm, useWatch } from 'react-hook-form';
import { CoverUpload } from '@/components/cover-upload';
import { FormField } from '@/components/form-field';
import { Button } from '@/components/ui/button';
import { Field, FieldControl, FieldError, FieldLabel } from '@/components/ui/field';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import { describeError } from '@/features/club-detail/describe-error';
import { showToast } from '@/lib/toast';
import { usePush } from '@/lib/use-push';
import { ErrorAlert, FormCard, VisibilitySwitch } from './club-form-parts';
import { useClubForEdit, useUpdateClub } from './use-organizer';

const valuesOf = (club: Club): EditClubForm => ({
  name: club.name,
  description: club.description ?? '',
  isPublic: club.isPublic,
  city: club.city ?? '',
  coverUrl: club.coverUrl ?? '',
  tags: club.tags.join(', '),
  meetingDurationMinutes: club.meetingDurationMinutes == null ? '' : String(club.meetingDurationMinutes),
  venueName: club.afterMeetingVenue?.name ?? '',
  venueAddress: club.afterMeetingVenue?.address ?? '',
  venueDescription: club.afterMeetingVenue?.description ?? '',
});

export function EditClub({ id }: { id: string }) {
  const t = useTranslations('EDIT_CLUB');
  const query = useClubForEdit(id);
  const club = query.data && !isClubStub(query.data) ? query.data : null;

  return (
    <FormCard subtitle={t('subtitle')} title={t('title')}>
      {query.isPending ? (
        <div className="flex justify-center py-12">
          <Spinner />
        </div>
      ) : club ? (
        <EditClubFormView club={club} />
      ) : (
        <ErrorAlert>{t('not_found')}</ErrorAlert>
      )}
    </FormCard>
  );
}

function EditClubFormView({ club }: { club: Club }) {
  const t = useTranslations('EDIT_CLUB');
  const tAll = useTranslations();
  const tErrors = useTranslations('ERRORS');
  const push = usePush();
  const update = useUpdateClub(club.id);
  const {
    register,
    handleSubmit,
    setValue,
    control,
    formState: { errors },
  } = useForm<EditClubForm>({ resolver: zodResolver(editClubForm), defaultValues: valuesOf(club), mode: 'onTouched' });
  const [isPublic, coverUrl] = useWatch({ control, name: ['isPublic', 'coverUrl'] });

  const submit = async (values: EditClubForm) => {
    if (update.isPending) return;
    const venueName = values.venueName.trim();
    const duration = values.meetingDurationMinutes.trim();
    try {
      await update.mutateAsync({
        name: values.name,
        description: values.description,
        isPublic: values.isPublic,
        city: values.city || undefined,
        coverUrl: values.coverUrl || null,
        tags: splitTags(values.tags),
        meetingDurationMinutes: duration === '' ? null : Number(duration),
        afterMeetingVenue: venueName ? { name: venueName, address: values.venueAddress.trim(), description: values.venueDescription.trim() } : null,
      });
      showToast('success', t('success'));
      push(`/clubs/${club.id}`);
    } catch {
      // surfaced through update.error
    }
  };

  return (
    <form onSubmit={handleSubmit(submit)} className="space-y-5" noValidate>
      <FormField
        id="club-name"
        type="text"
        data-testid="club-name-input"
        label={
          <>
            {t('name_label')}
            <span className="text-red-500" aria-hidden="true">
              *
            </span>
          </>
        }
        placeholder={t('name_placeholder')}
        error={errors.name?.message}
        {...register('name')}
      />

      <Field invalid={!!errors.description}>
        <FieldLabel className="text-sm font-medium text-gray-700 dark:text-gray-300">{t('description_label')}</FieldLabel>
        <FieldControl>
          <Textarea rows={3} className="resize-none" placeholder={t('description_placeholder')} {...register('description')} />
        </FieldControl>
        <FieldError className="text-xs">{errors.description?.message ? tAll(errors.description.message) : null}</FieldError>
      </Field>

      <FormField id="club-city" type="text" label={t('city_label')} placeholder={t('city_placeholder')} {...register('city')} />

      <div>
        <FormField id="club-tags" type="text" label={tAll('CLUB_MANAGE.tags_label')} placeholder={tAll('CLUB_MANAGE.tags_placeholder')} {...register('tags')} />
        <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">{tAll('CLUB_MANAGE.tags_hint')}</p>
      </div>

      <FormField
        id="club-duration"
        type="number"
        min={1}
        max={480}
        label={tAll('CLUB_MANAGE.duration_label')}
        placeholder={tAll('CLUB_MANAGE.duration_placeholder')}
        error={errors.meetingDurationMinutes?.message}
        {...register('meetingDurationMinutes')}
      />

      <fieldset className="space-y-3 rounded-xl border border-gray-200 dark:border-gray-700 p-4">
        <legend className="px-1 text-sm font-semibold text-gray-900 dark:text-white">{tAll('CLUB_MANAGE.venue_legend')}</legend>
        <FormField id="venue-name" type="text" label={tAll('CLUB_MANAGE.venue_name')} {...register('venueName')} />
        <FormField id="venue-address" type="text" label={tAll('CLUB_MANAGE.venue_address')} error={errors.venueAddress?.message} {...register('venueAddress')} />
        <Field>
          <FieldLabel className="text-sm font-medium text-gray-700 dark:text-gray-300">{tAll('CLUB_MANAGE.venue_description')}</FieldLabel>
          <FieldControl>
            <Textarea rows={2} className="resize-none" {...register('venueDescription')} />
          </FieldControl>
        </Field>
      </fieldset>

      <div>
        <p className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">{t('cover_url_label')}</p>
        <CoverUpload
          value={coverUrl}
          onChange={(url) => setValue('coverUrl', url, { shouldValidate: true })}
          invalid={!!errors.coverUrl}
          label={t('cover_url_label')}
          urlInputProps={errors.coverUrl ? { 'aria-describedby': 'club-cover-error' } : {}}
        />
        {errors.coverUrl?.message ? (
          <p id="club-cover-error" role="alert" className="mt-1 text-xs text-red-600 dark:text-red-400">
            {tAll(errors.coverUrl.message)}
          </p>
        ) : null}
      </div>

      <VisibilitySwitch legend={t('visibility_legend')} label={t('public_label')} description={t('public_desc')} checked={isPublic} onChange={(next) => setValue('isPublic', next)} />

      {update.isError ? <ErrorAlert>{describeError(update.error, tErrors)}</ErrorAlert> : null}

      <div className="flex gap-3 pt-2">
        <Button type="button" variant="outline" onClick={() => push(`/clubs/${club.id}`)} className="flex-1">
          {t('cancel')}
        </Button>
        <Button type="submit" disabled={update.isPending} data-testid="save-button" className="flex-1 bg-primary-600 hover:bg-primary-700 text-white">
          {update.isPending ? (
            <>
              <Spinner className="mr-2" />
              {t('submitting')}
            </>
          ) : (
            t('submit')
          )}
        </Button>
      </div>
    </form>
  );
}

// src/app/features/clubs/edit-club/edit-club.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
  input,
  OnInit,
} from '@angular/core';
import {
  ReactiveFormsModule,
  FormControl,
  FormGroup,
  Validators,
  AbstractControl,
  ValidationErrors,
} from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Router } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { toast } from '@spartan-ng/brain/sonner';
import { ClubService } from '../../../core/services/club.service';
import { CoverUploadComponent } from '../../../shared/components/cover-upload/cover-upload.component';
import { HlmFieldImports } from '../../../shared/spartan/field/src';
import { HlmInput } from '../../../shared/spartan/input/src';
import { HlmButton } from '../../../shared/spartan/button/src';
import { HlmSpinner } from '../../../shared/spartan/spinner/src';

function venueAddressRequired(control: AbstractControl): ValidationErrors | null {
  const name = (control.parent?.get('venueName')?.value as string | undefined)?.trim();
  const address = (control.value as string | null)?.trim();
  return name && !address ? { required: true } : null;
}

interface EditClubForm {
  name: FormControl<string>;
  description: FormControl<string>;
  isPublic: FormControl<boolean>;
  city: FormControl<string>;
  coverUrl: FormControl<string>;
  tags: FormControl<string>;
  meetingDurationMinutes: FormControl<number | null>;
  venueName: FormControl<string>;
  venueAddress: FormControl<string>;
  venueDescription: FormControl<string>;
}

@Component({
  selector: 'app-edit-club',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, TranslatePipe, CoverUploadComponent, ...HlmFieldImports, HlmInput, HlmButton, HlmSpinner],
  templateUrl: './edit-club.component.html',
})
export class EditClubComponent implements OnInit {
  readonly id = input.required<string>();

  private readonly clubService = inject(ClubService);
  private readonly router = inject(Router);
  private readonly translate = inject(TranslateService);

  private readonly _isLoadingClub = signal(true);
  readonly isLoadingClub = this._isLoadingClub.asReadonly();

  private readonly _isSubmitting = signal(false);
  readonly isSubmitting = this._isSubmitting.asReadonly();

  private readonly _errorMessage = signal<string | null>(null);
  readonly errorMessage = this._errorMessage.asReadonly();

  readonly form = new FormGroup<EditClubForm>({
    name: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(3), Validators.maxLength(100)],
    }),
    description: new FormControl('', {
      nonNullable: true,
      validators: [Validators.maxLength(500)],
    }),
    isPublic: new FormControl(true, { nonNullable: true }),
    city: new FormControl('', { nonNullable: true }),
    coverUrl: new FormControl('', { nonNullable: true, validators: [Validators.pattern(/^https?:\/\/.+\..+/)] }),
    tags: new FormControl('', { nonNullable: true }),
    meetingDurationMinutes: new FormControl<number | null>(null, {
      validators: [Validators.min(1), Validators.max(480)],
    }),
    venueName: new FormControl('', { nonNullable: true }),
    venueAddress: new FormControl('', { nonNullable: true, validators: [venueAddressRequired] }),
    venueDescription: new FormControl('', { nonNullable: true }),
  });

  constructor() {
    this.form.controls.venueName.valueChanges
      .pipe(takeUntilDestroyed())
      .subscribe(() => this.form.controls.venueAddress.updateValueAndValidity());
  }

  async ngOnInit(): Promise<void> {
    const club = await this.clubService.getClubById(this.id());
    if (!club) {
      this._errorMessage.set('Club not found.');
      this._isLoadingClub.set(false);
      return;
    }
    this.form.patchValue({
      name: club.name,
      description: club.description ?? '',
      isPublic: club.isPublic,
      city: club.city ?? '',
      coverUrl: club.coverUrl ?? '',
      tags: club.tags.join(', '),
      meetingDurationMinutes: club.meetingDurationMinutes,
      venueName: club.afterMeetingVenue?.name ?? '',
      venueAddress: club.afterMeetingVenue?.address ?? '',
      venueDescription: club.afterMeetingVenue?.description ?? '',
    });
    this._isLoadingClub.set(false);
  }

  togglePublic(): void {
    this.form.controls.isPublic.setValue(!this.form.controls.isPublic.value);
  }

  cancel(): void {
    this.router.navigate(['/clubs', this.id()]);
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this._isSubmitting.set(true);
    this._errorMessage.set(null);

    const {
      name, description, isPublic, city, coverUrl, tags,
      meetingDurationMinutes, venueName, venueAddress, venueDescription,
    } = this.form.getRawValue();
    const venueNameTrimmed = venueName.trim();
    try {
      await this.clubService.updateClub(this.id(), {
        name,
        description,
        isPublic,
        city: city || undefined,
        coverUrl: coverUrl || null,
        tags: tags.split(',').map(t => t.trim()).filter(Boolean),
        meetingDurationMinutes: meetingDurationMinutes ?? null,
        afterMeetingVenue: venueNameTrimmed
          ? { name: venueNameTrimmed, address: venueAddress.trim(), description: venueDescription.trim() }
          : null,
      });
      toast.success(this.translate.instant('EDIT_CLUB.success'));
      this.router.navigate(['/clubs', this.id()]);
    } catch (err) {
      this._errorMessage.set(err instanceof Error ? err.message : 'Failed to update club');
    } finally {
      this._isSubmitting.set(false);
    }
  }
}

<main class="min-h-screen flex items-center justify-center p-4">
  <div class="w-full max-w-lg">

    <header class="text-center mb-8">
      <h1 class="font-display text-3xl font-bold text-gray-900 dark:text-white">📚 BookClub</h1>
      <p class="text-gray-500 dark:text-gray-400 mt-2">{{ 'EDIT_CLUB.subtitle' | translate }}</p>
    </header>

    <article class="bg-white dark:bg-gray-900 rounded-2xl shadow-xl p-8">
      <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-6">{{ 'EDIT_CLUB.title' | translate }}</h2>

      @if (isLoadingClub()) {
        <div class="flex justify-center py-12">
          <app-loading-spinner />
        </div>
      } @else {
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-5" novalidate>

          <!-- Name -->
          <div>
            <label for="club-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ 'EDIT_CLUB.name_label' | translate }} <span class="text-red-500" aria-hidden="true">*</span>
            </label>
            <input
              id="club-name"
              type="text"
              formControlName="name"
              [placeholder]="'EDIT_CLUB.name_placeholder' | translate"
              class="w-full rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800
                     px-4 py-2.5 text-sm text-gray-900 dark:text-white placeholder-gray-400
                     focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent
                     transition-colors duration-150"
              [class.border-red-400]="form.controls.name.invalid && form.controls.name.touched"
              aria-describedby="name-error"
            />
            @if (form.controls.name.invalid && form.controls.name.touched) {
              <p id="name-error" class="mt-1 text-xs text-red-600 dark:text-red-400" role="alert">
                @if (form.controls.name.errors?.['required']) { {{ 'EDIT_CLUB.name_required' | translate }} }
                @else if (form.controls.name.errors?.['minlength']) { {{ 'EDIT_CLUB.name_min' | translate }} }
                @else if (form.controls.name.errors?.['maxlength']) { {{ 'EDIT_CLUB.name_max' | translate }} }
              </p>
            }
          </div>

          <!-- Description -->
          <div>
            <label for="club-description" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ 'EDIT_CLUB.description_label' | translate }}
            </label>
            <textarea
              id="club-description"
              formControlName="description"
              rows="3"
              [placeholder]="'EDIT_CLUB.description_placeholder' | translate"
              class="w-full rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800
                     px-4 py-2.5 text-sm text-gray-900 dark:text-white placeholder-gray-400 resize-none
                     focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent
                     transition-colors duration-150"
              [class.border-red-400]="form.controls.description.invalid && form.controls.description.touched"
              aria-describedby="description-error"
            ></textarea>
            @if (form.controls.description.invalid && form.controls.description.touched) {
              <p id="description-error" class="mt-1 text-xs text-red-600 dark:text-red-400" role="alert">
                @if (form.controls.description.errors?.['maxlength']) { {{ 'EDIT_CLUB.description_max' | translate }} }
              </p>
            }
          </div>

          <!-- City -->
          <div>
            <label for="club-city" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ 'EDIT_CLUB.city_label' | translate }}
            </label>
            <input
              id="club-city"
              type="text"
              formControlName="city"
              [placeholder]="'EDIT_CLUB.city_placeholder' | translate"
              class="w-full rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800
                     px-4 py-2.5 text-sm text-gray-900 dark:text-white placeholder-gray-400
                     focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent
                     transition-colors duration-150"
            />
          </div>

          <!-- Cover image URL -->
          <div>
            <label for="club-cover-url" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ 'EDIT_CLUB.cover_url_label' | translate }}
            </label>
            @if (form.controls.coverUrl.value) {
              <div class="mb-2 rounded-xl overflow-hidden h-28 bg-gray-100 dark:bg-gray-700">
                <img [src]="form.controls.coverUrl.value" alt="Cover preview" class="w-full h-full object-cover" (error)="form.controls.coverUrl.setValue('')" />
              </div>
            }
            <input
              id="club-cover-url"
              type="url"
              formControlName="coverUrl"
              [placeholder]="'EDIT_CLUB.cover_url_placeholder' | translate"
              class="w-full rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800
                     px-4 py-2.5 text-sm text-gray-900 dark:text-white placeholder-gray-400
                     focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent
                     transition-colors duration-150"
            />
            <p class="mt-1 text-xs text-gray-400 dark:text-gray-500">{{ 'EDIT_CLUB.cover_url_hint' | translate }}</p>
          </div>

          <!-- Visibility -->
          <fieldset>
            <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-3">{{ 'EDIT_CLUB.visibility_legend' | translate }}</legend>
            <div class="flex items-center justify-between rounded-xl bg-gray-50 dark:bg-gray-800 px-4 py-3">
              <div>
                <p class="text-sm font-medium text-gray-700 dark:text-gray-300">{{ 'EDIT_CLUB.public_label' | translate }}</p>
                <p class="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{{ 'EDIT_CLUB.public_desc' | translate }}</p>
              </div>
              <button
                type="button"
                role="switch"
                [attr.aria-checked]="form.controls.isPublic.value"
                (click)="togglePublic()"
                class="relative inline-flex h-6 w-11 items-center rounded-full transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
                [class.bg-primary-600]="form.controls.isPublic.value"
                [class.bg-gray-300]="!form.controls.isPublic.value"
                [class.dark:bg-gray-600]="!form.controls.isPublic.value"
              >
                <span
                  class="inline-block h-4 w-4 transform rounded-full bg-white shadow-sm transition-transform duration-200"
                  [class.translate-x-6]="form.controls.isPublic.value"
                  [class.translate-x-1]="!form.controls.isPublic.value"
                ></span>
              </button>
            </div>
          </fieldset>

          <!-- Error alert -->
          @if (errorMessage()) {
            <div
              class="flex items-start gap-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-400"
              role="alert"
            >
              <span class="mt-0.5 shrink-0" aria-hidden="true">⚠️</span>
              <span>{{ errorMessage() }}</span>
            </div>
          }

          <!-- Actions -->
          <div class="flex gap-3 pt-2">
            <button
              type="button"
              (click)="cancel()"
              class="flex-1 rounded-xl border border-gray-300 dark:border-gray-600 px-4 py-2.5
                     text-sm font-semibold text-gray-700 dark:text-gray-300
                     hover:bg-gray-50 dark:hover:bg-gray-800
                     focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2
                     transition-colors duration-200"
            >
              {{ 'EDIT_CLUB.cancel' | translate }}
            </button>
            <button
              type="submit"
              [disabled]="isSubmitting()"
              class="flex-1 flex items-center justify-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5
                     text-sm font-semibold text-white shadow-sm
                     hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2
                     disabled:opacity-60 disabled:cursor-not-allowed
                     transition-colors duration-200"
            >
              @if (isSubmitting()) {
                <app-loading-spinner size="sm" />
                {{ 'EDIT_CLUB.submitting' | translate }}
              } @else {
                {{ 'EDIT_CLUB.submit' | translate }}
              }
            </button>
          </div>

        </form>
      }
    </article>
  </div>
</main>
