// apps/web/src/features/profile/profile-stats.tsx
import type { UserStats } from '@book-club/contracts';
import { BookIcon, BookOpenIcon, BrainIcon, HeartIcon, TrophyIcon } from 'lucide-react';
import { useTranslations } from 'next-intl';

const TILES = [
  { key: 'clubsJoined', label: 'clubs_joined', Icon: BookOpenIcon, border: 'border-primary-500', text: 'text-primary-500' },
  { key: 'quizzesTaken', label: 'quizzes_taken', Icon: BrainIcon, border: 'border-accent-500', text: 'text-accent-500' },
  { key: 'quizWins', label: 'quizzes_won', Icon: TrophyIcon, border: 'border-amber-500', text: 'text-amber-500' },
  { key: 'likesReceived', label: 'likes_received', Icon: HeartIcon, border: 'border-rose-500', text: 'text-rose-500' },
  { key: 'booksRead', label: 'books_read', Icon: BookIcon, border: 'border-teal-500', text: 'text-teal-500' },
] as const;

export function ProfileStats({ stats }: { stats: UserStats | null }) {
  const t = useTranslations('PROFILE');
  return (
    <>
      <dl className="bento-grid-3">
        {TILES.map(({ key, label, Icon, border, text }) => (
          <div key={key} className={`parchment-card-raised border-t-4 p-5 text-center ${border}`}>
            <div className={`flex justify-center mb-2 ${text}`} aria-hidden="true">
              <Icon size={28} />
            </div>
            <dt className="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{t(label)}</dt>
            <dd className="heading-display text-4xl font-bold text-[var(--color-ink)]">{stats?.[key] ?? 0}</dd>
          </div>
        ))}
      </dl>
      {!stats && <p className="text-center text-sm text-gray-400 dark:text-gray-500 mt-4">{t('no_stats')}</p>}
    </>
  );
}

// src/app/features/profile/stats/profile-stats.component.ts
import { Component, ChangeDetectionStrategy, input } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBookOpen, lucideBrain, lucideTrophy, lucideHeart, lucideBook } from '@ng-icons/lucide';
import { UserStats } from '../../../core/models/user.model';

@Component({
  selector: 'app-profile-stats',
  standalone: true,
  imports: [TranslateModule, NgIcon],
  providers: [provideIcons({ lucideBookOpen, lucideBrain, lucideTrophy, lucideHeart, lucideBook })],
  templateUrl: './profile-stats.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProfileStatsComponent {
  readonly stats = input<UserStats | null | undefined>(null);
}

<dl class="bento-grid-3">

  <div class="parchment-card-raised border-t-4 border-primary-500 p-5 text-center">
    <div class="flex justify-center mb-2 text-primary-500" aria-hidden="true">
      <ng-icon name="lucideBookOpen" size="28" />
    </div>
    <dt class="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{{ 'PROFILE.clubs_joined' | translate }}</dt>
    <dd class="heading-display text-4xl font-bold text-[var(--color-ink)]">{{ stats()?.clubsJoined ?? 0 }}</dd>
  </div>

  <div class="parchment-card-raised border-t-4 border-accent-500 p-5 text-center">
    <div class="flex justify-center mb-2 text-accent-500" aria-hidden="true">
      <ng-icon name="lucideBrain" size="28" />
    </div>
    <dt class="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{{ 'PROFILE.quizzes_taken' | translate }}</dt>
    <dd class="heading-display text-4xl font-bold text-[var(--color-ink)]">{{ stats()?.quizzesTaken ?? 0 }}</dd>
  </div>

  <div class="parchment-card-raised border-t-4 border-amber-500 p-5 text-center">
    <div class="flex justify-center mb-2 text-amber-500" aria-hidden="true">
      <ng-icon name="lucideTrophy" size="28" />
    </div>
    <dt class="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{{ 'PROFILE.quizzes_won' | translate }}</dt>
    <dd class="heading-display text-4xl font-bold text-[var(--color-ink)]">{{ stats()?.quizWins ?? 0 }}</dd>
  </div>

  <div class="parchment-card-raised border-t-4 border-rose-500 p-5 text-center">
    <div class="flex justify-center mb-2 text-rose-500" aria-hidden="true">
      <ng-icon name="lucideHeart" size="28" />
    </div>
    <dt class="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{{ 'PROFILE.likes_received' | translate }}</dt>
    <dd class="heading-display text-4xl font-bold text-[var(--color-ink)]">{{ stats()?.likesReceived ?? 0 }}</dd>
  </div>

  <div class="parchment-card-raised border-t-4 border-teal-500 p-5 text-center">
    <div class="flex justify-center mb-2 text-teal-500" aria-hidden="true">
      <ng-icon name="lucideBook" size="28" />
    </div>
    <dt class="text-xs uppercase tracking-widest text-[var(--color-ink-muted)] mt-1">{{ 'PROFILE.books_read' | translate }}</dt>
    <dd class="heading-display text-4xl font-bold text-[var(--color-ink)]">{{ stats()?.booksRead ?? 0 }}</dd>
  </div>

</dl>

@if (!stats()) {
  <p class="text-center text-sm text-gray-400 dark:text-gray-500 mt-4">
    {{ 'PROFILE.no_stats' | translate }}
  </p>
}
