// src/app/shared/components/social-link-field/social-link-field.component.ts
import { Component, input } from '@angular/core';
import { ReactiveFormsModule, FormGroup } from '@angular/forms';

export interface SocialField {
  key: string;
  label: string;
  labelClass: string;
  placeholder: string;
  focusRingClass: string;
}

@Component({
  selector: 'app-social-link-field',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './social-link-field.component.html',
})
export class SocialLinkFieldComponent {
  readonly config = input.required<SocialField>();
  readonly form = input.required<FormGroup>();
}

<div>
  <label
    [for]="'social-' + config().key"
    class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5"
  >
    <span [class]="config().labelClass">{{ config().label }}</span>
  </label>
  <input
    [id]="'social-' + config().key"
    type="text"
    [formControl]="$any(form().controls)[config().key]"
    [placeholder]="config().placeholder"
    autocomplete="off"
    class="w-full rounded-xl border border-gray-200 dark:border-gray-700
           bg-gray-50 dark:bg-gray-900 px-4 py-2.5 text-sm
           text-gray-900 dark:text-white placeholder-gray-400
           focus:outline-none focus:ring-2 focus:border-transparent
           transition-all duration-200"
    [class]="config().focusRingClass"
  />
</div>

// apps/web/src/components/social-link-field.tsx
'use client';

import type { ComponentProps } from 'react';
import { Field, FieldControl, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';

export interface SocialField {
  key: string;
  label: string;
  labelClass: string;
  placeholder: string;
  focusRingClass: string;
}

type Props = { config: SocialField } & Omit<ComponentProps<typeof Input>, 'placeholder' | 'type'>;

/** One social-network input; the `register(...)` props of the owning form go in `...input`. */
export function SocialLinkField({ config, className, ...input }: Props) {
  return (
    <Field className="gap-1.5">
      <FieldLabel className="text-sm font-medium text-gray-700 dark:text-gray-300">
        <span className={config.labelClass}>{config.label}</span>
      </FieldLabel>
      <FieldControl>
        <Input
          type="text"
          autoComplete="off"
          placeholder={config.placeholder}
          data-testid={`social-${config.key}`}
          className={cn('h-auto rounded-xl border-gray-200 bg-gray-50 px-4 py-2.5 text-sm dark:border-gray-700 dark:bg-gray-900', config.focusRingClass, className)}
          {...input}
        />
      </FieldControl>
    </Field>
  );
}
