// apps/web/src/features/randomizer/randomizer.tsx
'use client';
'use no memo';

import { useQueryClient } from '@tanstack/react-query';
import type { ClubMember, RandomizerSession } from '@book-club/contracts';
import { useLocale, useTranslations } from 'next-intl';
import { useEffect, useMemo, useRef, useState } from 'react';
import { AppLink } from '@/components/app-link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import { useClubMembers } from '@/features/club-detail/use-club-detail';
import { useGuardedRunner, useMounted } from '@/features/club-manage/use-club-manage';
import { api } from '@/lib/api';
import { initials } from '@/lib/format';
import { cn } from '@/lib/utils';
import { pickIndex } from './pick';
import { historyKey, useRandomizerHistory } from './use-randomizer';

const SPIN_MS = 2000;
const MIN_PARTICIPANTS = 2;
const HISTORY_SHOWN = 5;
const LOCALES: Record<string, string> = { uk: 'uk-UA', en: 'en-US' };
const TIME_ZONE = 'Europe/Kyiv';

const stamp = (value: string, locale: string) => {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return date.toLocaleString(LOCALES[locale] ?? 'en-US', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false, timeZone: TIME_ZONE });
};

export function Randomizer({ clubId }: { clubId: string }) {
  const t = useTranslations('RANDOMIZER');
  const locale = useLocale();
  const queryClient = useQueryClient();
  const membersQuery = useClubMembers(clubId, true);
  const history = useRandomizerHistory(clubId).data ?? [];
  const { run, busy } = useGuardedRunner();
  const isMounted = useMounted();

  const [purpose, setPurpose] = useState(() => t('default_purpose'));
  const [excluded, setExcluded] = useState<ReadonlySet<string>>(() => new Set());
  const [result, setResult] = useState<ClubMember | null>(null);
  const [spinning, setSpinning] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const spinGuard = useRef(false);

  useEffect(() => () => clearTimeout(timer.current), []);

  const candidates = useMemo(() => membersQuery.data ?? [], [membersQuery.data]);
  const selected = useMemo(() => candidates.filter((m) => !excluded.has(m.userId)), [candidates, excluded]);
  const canSpin = selected.length >= MIN_PARTICIPANTS;

  const toggle = (userId: string) =>
    setExcluded((prev) => {
      const next = new Set(prev);
      if (!next.delete(userId)) next.add(userId);
      return next;
    });

  const reset = () => {
    setExcluded(new Set());
    setResult(null);
  };

  const spin = () => {
    if (spinGuard.current || !canSpin) return;
    spinGuard.current = true;
    setSpinning(true);
    setResult(null);
    const pool = selected;
    timer.current = setTimeout(() => {
      spinGuard.current = false;
      if (!isMounted()) return;
      setResult(pool[pickIndex(pool.length)] ?? null);
      setSpinning(false);
    }, SPIN_MS);
  };

  const save = () =>
    run('save', async () => {
      if (!result) return;
      const session = await api.randomizer.createSession(clubId, {
        purpose,
        candidates: selected.map((m) => ({ userId: m.userId, displayName: m.displayName, avatarUrl: m.avatarUrl })),
        result: { userId: result.userId, displayName: result.displayName, avatarUrl: result.avatarUrl },
      });
      queryClient.setQueryData<RandomizerSession[]>(historyKey(clubId), (list) => [session, ...(list ?? [])]);
    });

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-primary-900 to-slate-900 p-4 sm:p-8">
      <div className="max-w-4xl mx-auto space-y-8">
        <header className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="font-display text-3xl font-bold text-white">
              <span aria-hidden="true">🎲 </span>
              {t('title')}
            </h1>
            <p className="text-primary-300 mt-1">{t('subtitle')}</p>
          </div>
          <nav aria-label="Breadcrumb">
            <AppLink href={`/clubs/${clubId}`} className="text-primary-300 hover:text-white transition-colors text-sm">
              {t('back_to_club')}
            </AppLink>
          </nav>
        </header>

        <div className="bg-white/10 backdrop-blur rounded-2xl p-5 border border-white/10">
          <label htmlFor="purpose" className="block text-white font-medium text-sm mb-2">
            {t('purpose_label')}
          </label>
          <Input id="purpose" type="text" value={purpose} onChange={(e) => setPurpose(e.target.value)} placeholder={t('purpose_placeholder')} className="w-full rounded-xl bg-white/10 border-white/20 text-white placeholder-white/40 px-4" />
        </div>

        <div className="grid lg:grid-cols-2 gap-8">
          <section aria-labelledby="members-heading" className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 id="members-heading" className="text-white font-semibold text-lg">
                <span aria-hidden="true">👥 </span>
                {t('members_title')}
                <span className="text-primary-300 text-sm font-normal ml-2">
                  {selected.length} / {candidates.length} {t('selected')}
                </span>
              </h2>
              <Button type="button" variant="ghost" size="sm" onClick={reset} className="text-xs text-primary-300 hover:text-white">
                {t('select_all')}
              </Button>
            </div>

            {membersQuery.isPending ? (
              <div className="flex justify-center py-8" aria-busy="true">
                <Spinner />
              </div>
            ) : candidates.length === 0 ? (
              <div className="bg-white/10 rounded-2xl p-8 text-center text-white/60">
                <p className="text-3xl mb-2">👤</p>
                <p>{t('no_members')}</p>
              </div>
            ) : (
              <ul className="space-y-2">
                {candidates.map((member) => {
                  const on = !excluded.has(member.userId);
                  return (
                    <li key={member.userId}>
                      <button
                        type="button"
                        onClick={() => toggle(member.userId)}
                        aria-pressed={on}
                        className={cn('w-full flex items-center gap-3 rounded-xl p-3 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-400', on ? 'bg-white/20 border border-white/30' : 'bg-white/5 border border-white/10 opacity-50')}
                      >
                        <span className="h-10 w-10 rounded-full bg-gradient-to-br from-primary-400 to-accent-500 flex items-center justify-center text-white text-sm font-bold shrink-0" aria-hidden="true">
                          {initials(member.displayName)}
                        </span>
                        <span className="text-white font-medium text-sm flex-1 text-left">{member.displayName}</span>
                        {on ? (
                          <span className="text-green-400 text-lg" aria-hidden="true">
                            ✓
                          </span>
                        ) : null}
                      </button>
                    </li>
                  );
                })}
              </ul>
            )}
          </section>

          <section aria-labelledby="spin-heading" className="space-y-6">
            <h2 id="spin-heading" className="sr-only">
              {t('title')}
            </h2>

            <div className="bg-white/10 backdrop-blur rounded-2xl p-8 border border-white/10 text-center min-h-[200px] flex flex-col items-center justify-center" aria-live="polite">
              {spinning ? (
                <div className="space-y-4">
                  <div className="text-5xl animate-bounce" aria-hidden="true">
                    🎲
                  </div>
                  <p className="text-white/70 text-sm animate-pulse">{t('spinning')}</p>
                </div>
              ) : result ? (
                <div className="space-y-3" data-testid="randomizer-result">
                  <div className="h-20 w-20 mx-auto rounded-full bg-gradient-to-br from-accent-400 to-primary-500 flex items-center justify-center text-white text-2xl font-bold shadow-xl ring-4 ring-white/30" aria-hidden="true">
                    {initials(result.displayName)}
                  </div>
                  <div>
                    <p className="text-white/60 text-xs uppercase tracking-wide mb-1">{purpose}</p>
                    <p className="text-white text-2xl font-bold">{result.displayName}</p>
                  </div>
                  <span className="text-3xl" aria-hidden="true">
                    🏆
                  </span>
                </div>
              ) : (
                <div className="text-white/40 space-y-2">
                  <div className="text-4xl" aria-hidden="true">
                    🎯
                  </div>
                  <p className="text-sm">{t('spin_hint')}</p>
                </div>
              )}
            </div>

            <div className="flex flex-col gap-3">
              <Button type="button" data-testid="spin-button" onClick={spin} disabled={spinning || !canSpin} className="w-full rounded-2xl bg-gradient-to-r from-accent-500 to-primary-500 hover:from-accent-400 hover:to-primary-400 text-white font-bold py-4 text-lg shadow-lg h-auto">
                {spinning ? t('spinning_btn') : t('spin')}
              </Button>

              {!canSpin && !spinning ? <p className="text-center text-white/50 text-xs">{t('error_min')}</p> : null}

              {result && !spinning ? (
                <Button type="button" variant="outline" onClick={() => void save()} disabled={busy.has('save')} className="w-full rounded-2xl bg-white/10 hover:bg-white/20 border-white/20 text-white font-medium py-3 h-auto">
                  {busy.has('save') ? t('saving') : t('save')}
                </Button>
              ) : null}
            </div>

            {history.length > 0 ? (
              <div className="space-y-3">
                <h3 className="text-white/70 text-sm font-medium uppercase tracking-wide">{t('history_title')}</h3>
                <ul className="space-y-2">
                  {history.slice(0, HISTORY_SHOWN).map((session) => (
                    <li key={session.id} className="bg-white/5 rounded-xl px-4 py-3 flex items-center justify-between gap-3">
                      <div className="min-w-0">
                        <p className="text-white/60 text-xs truncate">{session.purpose}</p>
                        {session.result ? (
                          <p className="text-white text-sm font-medium">
                            <span aria-hidden="true">🏆 </span>
                            {session.result.displayName}
                          </p>
                        ) : null}
                      </div>
                      <span className="text-white/40 text-xs shrink-0">{stamp(session.createdAt, locale)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </section>
        </div>
      </div>
    </div>
  );
}

// src/app/features/randomizer/randomizer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  inject,
  signal,
  computed,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ReactiveFormsModule, FormControl, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { AuthService } from '../../core/auth/auth.service';
import { RandomizerService } from '../../core/services/randomizer.service';

@Component({
  selector: 'app-randomizer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, RouterLink, DatePipe, TranslateModule],
  styleUrl: './randomizer.component.scss',
  templateUrl: './randomizer.component.html',
})
export class RandomizerComponent implements OnInit {
  protected readonly randomizerService = inject(RandomizerService);
  protected readonly authService = inject(AuthService);
  private readonly route = inject(ActivatedRoute);

  protected readonly isSaving = signal(false);
  protected readonly errorMessage = signal('');
  protected clubId = '';

  protected readonly purposeControl = new FormControl('Хто представляє книгу?', {
    nonNullable: true,
    validators: [Validators.required],
  });

  // toSignal keeps OnPush change detection working without manual markForCheck
  private readonly _purposeValue = toSignal(this.purposeControl.valueChanges, {
    initialValue: this.purposeControl.value,
  });

  protected readonly selectedCount = computed(
    () =>
      this.randomizerService
        .candidates()
        .filter(m => this.randomizerService.selectedIds().has(m.userId)).length,
  );

  protected readonly initials = (name: string): string =>
    name
      .split(' ')
      .map(w => w[0])
      .join('')
      .toUpperCase()
      .slice(0, 2);

  ngOnInit(): void {
    this.clubId = this.route.snapshot.params['id'] as string;
    this.randomizerService.loadClubMembers(this.clubId);
    this.randomizerService.setPurpose(this.purposeControl.value);

    // Sync purpose input → service via the signal derived from valueChanges
    // effect() would be ideal here but we keep it simple with a subscription
    // that is automatically cleaned up when the component destroys
    this.purposeControl.valueChanges.subscribe(v =>
      this.randomizerService.setPurpose(v),
    );

    this.randomizerService.loadHistory(this.clubId).catch(() => {});
  }

  protected spin(): void {
    this.errorMessage.set('');
    this.randomizerService.spin().catch(err => {
      this.errorMessage.set((err as Error).message);
    });
  }

  protected saveSession(): void {
    this.isSaving.set(true);
    this.errorMessage.set('');
    this.randomizerService
      .saveSession(this.clubId)
      .then(() => this.isSaving.set(false))
      .catch(err => {
        this.isSaving.set(false);
        this.errorMessage.set((err as Error).message);
      });
  }

  protected reset(): void {
    this.randomizerService.reset();
    this.errorMessage.set('');
  }
}

<div class="min-h-screen bg-gradient-to-br from-slate-900 via-primary-900 to-slate-900 p-4 sm:p-8">
  <div class="max-w-4xl mx-auto space-y-8">

    <!-- ── Header ── -->
    <header class="flex items-center justify-between flex-wrap gap-4">
      <div>
        <h1 class="font-display text-3xl font-bold text-white">🎲 {{ 'RANDOMIZER.title' | translate }}</h1>
        <p class="text-primary-300 mt-1">{{ 'RANDOMIZER.subtitle' | translate }}</p>
      </div>
      <nav aria-label="Breadcrumb">
        <a [routerLink]="['/clubs', clubId]" class="text-primary-300 hover:text-white transition-colors text-sm">
          {{ 'RANDOMIZER.back_to_club' | translate }}
        </a>
      </nav>
    </header>

    <!-- ── Purpose input ── -->
    <div class="bg-white/10 backdrop-blur rounded-2xl p-5 border border-white/10">
      <label for="purpose" class="block text-white font-medium text-sm mb-2">{{ 'RANDOMIZER.purpose_label' | translate }}</label>
      <input
        id="purpose"
        type="text"
        [formControl]="purposeControl"
        [placeholder]="'RANDOMIZER.purpose_placeholder' | translate"
        class="w-full rounded-xl bg-white/10 border border-white/20 text-white placeholder-white/40 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary-400"
      />
    </div>

    <div class="grid lg:grid-cols-2 gap-8">

      <!-- ── Left: Members list ── -->
      <section aria-labelledby="members-heading" class="space-y-4">
        <div class="flex items-center justify-between">
          <h2 id="members-heading" class="text-white font-semibold text-lg">
            👥 {{ 'RANDOMIZER.members_title' | translate }}
            <span class="text-primary-300 text-sm font-normal ml-2">{{ selectedCount() }} / {{ randomizerService.candidates().length }} {{ 'RANDOMIZER.selected' | translate }}</span>
          </h2>
          <button
            type="button"
            (click)="reset()"
            class="text-xs text-primary-300 hover:text-white transition-colors"
          >
            {{ 'RANDOMIZER.select_all' | translate }}
          </button>
        </div>

        @if (randomizerService.candidates().length === 0) {
          <div class="bg-white/10 rounded-2xl p-8 text-center text-white/60">
            <p class="text-3xl mb-2">👤</p>
            <p>{{ 'RANDOMIZER.no_members' | translate }}</p>
          </div>
        } @else {
          <ul class="space-y-2" role="list">
            @for (member of randomizerService.candidates(); track member.userId) {
              <li>
                <button
                  type="button"
                  (click)="randomizerService.toggleMember(member.userId)"
                  class="w-full flex items-center gap-3 rounded-xl p-3 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-400"
                  [class]="randomizerService.selectedIds().has(member.userId)
                    ? 'bg-white/20 border border-white/30'
                    : 'bg-white/5 border border-white/10 opacity-50'"
                  [attr.aria-pressed]="randomizerService.selectedIds().has(member.userId)"
                  [attr.aria-label]="'Toggle ' + member.displayName"
                >
                  <!-- Avatar -->
                  <div class="h-10 w-10 rounded-full bg-gradient-to-br from-primary-400 to-accent-500 flex items-center justify-center text-white text-sm font-bold shrink-0">
                    {{ initials(member.displayName) }}
                  </div>
                  <span class="text-white font-medium text-sm flex-1 text-left">{{ member.displayName }}</span>
                  @if (randomizerService.selectedIds().has(member.userId)) {
                    <span class="text-green-400 text-lg" aria-hidden="true">✓</span>
                  }
                </button>
              </li>
            }
          </ul>
        }
      </section>

      <!-- ── Right: Spin + Result ── -->
      <section aria-labelledby="spin-heading" class="space-y-6">
        <h2 id="spin-heading" class="sr-only">{{ 'RANDOMIZER.title' | translate }}</h2>

        <!-- Result display -->
        <div class="bg-white/10 backdrop-blur rounded-2xl p-8 border border-white/10 text-center min-h-[200px] flex flex-col items-center justify-center">
          @if (randomizerService.isSpinning()) {
            <div class="space-y-4">
              <div class="text-5xl animate-bounce">🎲</div>
              <p class="text-white/70 text-sm animate-pulse">{{ 'RANDOMIZER.spinning' | translate }}</p>
            </div>
          } @else if (randomizerService.result()) {
            <div class="space-y-3">
              <div class="h-20 w-20 mx-auto rounded-full bg-gradient-to-br from-accent-400 to-primary-500 flex items-center justify-center text-white text-2xl font-bold shadow-xl ring-4 ring-white/30">
                {{ initials(randomizerService.result()!.displayName) }}
              </div>
              <div>
                <p class="text-white/60 text-xs uppercase tracking-wide mb-1">{{ randomizerService.purpose() }}</p>
                <p class="text-white text-2xl font-bold">{{ randomizerService.result()!.displayName }}</p>
              </div>
              <span class="text-3xl">🏆</span>
            </div>
          } @else {
            <div class="text-white/40 space-y-2">
              <div class="text-4xl">🎯</div>
              <p class="text-sm">{{ 'RANDOMIZER.spin_hint' | translate }}</p>
            </div>
          }
        </div>

        <!-- Error -->
        @if (errorMessage()) {
          <div class="rounded-xl bg-red-500/20 border border-red-500/30 px-4 py-3 text-sm text-red-300" role="alert">
            {{ errorMessage() }}
          </div>
        }

        <!-- Action buttons -->
        <div class="flex flex-col gap-3">
          <button
            type="button"
            (click)="spin()"
            [disabled]="randomizerService.isSpinning() || selectedCount() < 2"
            class="w-full rounded-2xl bg-gradient-to-r from-accent-500 to-primary-500 hover:from-accent-400 hover:to-primary-400 text-white font-bold py-4 text-lg transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-primary-400 shadow-lg"
          >
            @if (randomizerService.isSpinning()) {
              {{ 'RANDOMIZER.spinning_btn' | translate }}
            } @else {
              {{ 'RANDOMIZER.spin' | translate }}
            }
          </button>

          @if (randomizerService.result() && authService.isOrganizer()) {
            <button
              type="button"
              (click)="saveSession()"
              [disabled]="isSaving()"
              class="w-full rounded-2xl bg-white/10 hover:bg-white/20 border border-white/20 text-white font-medium py-3 transition-all duration-200 disabled:opacity-50 focus:outline-none focus:ring-2 focus:ring-primary-400"
            >
              @if (isSaving()) {
                {{ 'RANDOMIZER.saving' | translate }}
              } @else {
                {{ 'RANDOMIZER.save' | translate }}
              }
            </button>
          }
        </div>

        <!-- History -->
        @if (randomizerService.history().length > 0) {
          <div class="space-y-3">
            <h3 class="text-white/70 text-sm font-medium uppercase tracking-wide">{{ 'RANDOMIZER.history_title' | translate }}</h3>
            <ul class="space-y-2" role="list">
              @for (session of randomizerService.history().slice(0, 5); track session.id) {
                <li class="bg-white/5 rounded-xl px-4 py-3 flex items-center justify-between gap-3">
                  <div class="min-w-0">
                    <p class="text-white/60 text-xs truncate">{{ session.purpose }}</p>
                    @if (session.result) {
                      <p class="text-white text-sm font-medium">🏆 {{ session.result.displayName }}</p>
                    }
                  </div>
                  <span class="text-white/40 text-xs shrink-0">{{ session.createdAt | date:'dd.MM HH:mm' }}</span>
                </li>
              }
            </ul>
          </div>
        }

      </section>
    </div>
  </div>
</div>
