// apps/web/src/components/cover-upload.tsx
'use client';

import { useTranslations } from 'next-intl';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Spinner } from '@/components/ui/spinner';
import { api } from '@/lib/api';

/** What the picker offers and what the backend would accept (it also allows gif, which the picker never has). */
const ACCEPT = ['image/jpeg', 'image/png', 'image/webp'];
export const MAX_COVER_BYTES = 5 * 1024 * 1024;

interface Props {
  value: string;
  onChange: (url: string) => void;
  invalid?: boolean;
  urlInputProps?: { id?: string; 'aria-describedby'?: string };
}

const isWebUrl = (src: string) => /^https?:\/\//i.test(src);

export function CoverUpload({ value, onChange, invalid = false, urlInputProps }: Props) {
  const t = useTranslations('COVER_UPLOAD');
  const [uploading, setUploading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showUrl, setShowUrl] = useState(false);
  const [preview, setPreview] = useState<string | null>(null);
  const [uploadedUrl, setUploadedUrl] = useState<string | null>(null);
  const [brokenSrc, setBrokenSrc] = useState<string | null>(null);
  const fileInput = useRef<HTMLInputElement>(null);
  const mounted = useRef(true);
  const previewRef = useRef<string | null>(null);

  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      if (previewRef.current) URL.revokeObjectURL(previewRef.current);
    };
  }, []);

  const setLocalPreview = (next: string | null) => {
    if (previewRef.current) URL.revokeObjectURL(previewRef.current);
    previewRef.current = next;
    setPreview(next);
  };

  const clear = () => {
    setLocalPreview(null);
    onChange('');
  };

  const upload = async (file: File) => {
    setError(null);
    if (!ACCEPT.includes(file.type) || file.size > MAX_COVER_BYTES) {
      setError(t('upload_failed'));
      return;
    }
    setLocalPreview(URL.createObjectURL(file));
    setUploading(true);
    const form = new FormData();
    form.append('file', file);
    try {
      const { url } = await api.upload.cover(form);
      if (!mounted.current) return;
      setUploadedUrl(url);
      onChange(url);
    } catch {
      if (!mounted.current) return;
      setError(t('upload_failed'));
      setLocalPreview(null);
    } finally {
      if (mounted.current) setUploading(false);
    }
  };

  // the local preview stands in for the uploaded file only while the field still holds that upload
  const local = preview !== null && (uploading || value === uploadedUrl) ? preview : null;
  const src = local ?? (isWebUrl(value) ? value : '');

  return (
    <div className="space-y-2">
      {src && src !== brokenSrc ? (
        <div className="relative h-28 overflow-hidden rounded-xl bg-gray-100 dark:bg-gray-700">
          {/* eslint-disable-next-line @next/next/no-img-element -- cover URLs are arbitrary hosts; no image optimizer is configured */}
          <img src={src} alt="" referrerPolicy="no-referrer" className="size-full object-cover" onError={() => setBrokenSrc(src)} />
          <button
            type="button"
            onClick={clear}
            aria-label={t('remove')}
            className="absolute right-1 top-1 rounded-full bg-black/50 px-2 py-0.5 text-xs text-white transition-colors hover:bg-black/70"
          >
            ✕
          </button>
        </div>
      ) : null}
      <div className="flex gap-2">
        <Button type="button" variant="outline" disabled={uploading} onClick={() => fileInput.current?.click()} data-testid="cover-upload-button">
          {uploading ? (
            <>
              <Spinner /> {t('uploading')}
            </>
          ) : (
            t('upload_image')
          )}
        </Button>
        <Button type="button" variant="outline" aria-expanded={showUrl} onClick={() => setShowUrl((v) => !v)}>
          {showUrl ? t('hide_url') : t('enter_url')}
        </Button>
      </div>
      {showUrl ? (
        <Input
          type="url"
          value={value}
          onChange={(e) => {
            setLocalPreview(null);
            onChange(e.target.value);
          }}
          placeholder="https://example.com/cover.jpg"
          aria-invalid={invalid || undefined}
          data-testid="cover-url-input"
          {...urlInputProps}
        />
      ) : null}
      {error ? (
        <p role="alert" className="text-xs text-red-600 dark:text-red-400">
          {error}
        </p>
      ) : null}
      <input
        ref={fileInput}
        type="file"
        accept={ACCEPT.join(',')}
        className="hidden"
        data-testid="cover-file-input"
        tabIndex={-1}
        aria-hidden="true"
        onChange={(e) => {
          const file = e.target.files?.[0];
          e.target.value = '';
          if (file) void upload(file);
        }}
      />
    </div>
  );
}

// src/app/shared/components/cover-upload/cover-upload.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  DestroyRef,
  inject,
  signal,
  input,
  effect,
} from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { UploadService } from '../../../core/services/upload.service';

@Component({
  selector: 'app-cover-upload',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, TranslateModule],
  template: `
    <div class="space-y-2">
      @if (previewUrl() || externalUrl()) {
        <div class="relative rounded-xl overflow-hidden h-28 bg-gray-100 dark:bg-gray-700">
          <img
            [src]="previewUrl() || externalUrl()"
            alt="Cover preview"
            class="w-full h-full object-cover"
            (error)="clearPreview()"
          />
          <button
            type="button"
            (click)="clearPreview()"
            class="absolute top-1 right-1 rounded-full bg-black/50 text-white text-xs px-2 py-0.5 hover:bg-black/70 transition-colors"
          >✕</button>
        </div>
      }

      <div class="flex gap-2">
        <button
          type="button"
          (click)="fileInput.click()"
          [disabled]="isUploading()"
          class="inline-flex items-center gap-1.5 rounded-xl border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 disabled:opacity-50 transition-colors"
        >
          @if (isUploading()) {
            <span class="animate-spin">⏳</span> {{ 'COVER_UPLOAD.uploading' | translate }}
          } @else {
            {{ 'COVER_UPLOAD.upload_image' | translate }}
          }
        </button>

        <button
          type="button"
          (click)="showUrlInput.set(!showUrlInput())"
          class="inline-flex items-center gap-1.5 rounded-xl border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors"
        >
          {{ (showUrlInput() ? 'COVER_UPLOAD.hide_url' : 'COVER_UPLOAD.enter_url') | translate }}
        </button>
      </div>

      @if (showUrlInput()) {
        <input
          type="url"
          [formControl]="control()"
          placeholder="https://example.com/cover.jpg"
          class="w-full rounded-xl border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 px-3 py-2 text-sm text-gray-900 dark:text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500"
        />
      }

      @if (uploadError()) {
        <p class="text-xs text-red-600 dark:text-red-400">{{ uploadError() }}</p>
      }

      <input
        #fileInput
        type="file"
        accept="image/jpeg,image/png,image/webp"
        class="hidden"
        (change)="onFileSelected($event)"
      />
    </div>
  `,
})
export class CoverUploadComponent {
  readonly control = input.required<FormControl<string>>();

  private readonly uploadService = inject(UploadService);
  private readonly destroyRef = inject(DestroyRef);
  private readonly translate = inject(TranslateService);

  readonly isUploading = signal(false);
  readonly uploadError = signal<string | null>(null);
  readonly showUrlInput = signal(false);
  readonly previewUrl = signal<string | null>(null);
  readonly externalUrl = signal<string>('');

  constructor() {
    effect(onCleanup => {
      const ctrl = this.control();
      this.externalUrl.set(ctrl.value);
      const sub = ctrl.valueChanges.subscribe(v => this.externalUrl.set(v ?? ''));
      onCleanup(() => sub.unsubscribe());
    });
  }

  clearPreview(): void {
    this.previewUrl.set(null);
    this.control().setValue('');
  }

  onFileSelected(event: Event): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    if (!file) return;

    this.previewUrl.set(URL.createObjectURL(file));
    this.uploadError.set(null);
    this.isUploading.set(true);

    this.uploadService.uploadCover$(file).subscribe({
      next: url => {
        this.control().setValue(url);
        this.isUploading.set(false);
      },
      error: () => {
        this.uploadError.set(this.translate.instant('COVER_UPLOAD.upload_failed'));
        this.isUploading.set(false);
        this.previewUrl.set(null);
      },
    });
  }
}
