// apps/web/src/features/support/create-submission.tsx
'use client';
'use no memo';

import { zodResolver } from '@hookform/resolvers/zod';
import { createSubmissionForm, type CreateSubmissionForm } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import { useForm } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { Field, FieldControl, FieldError, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import { describeError } from '@/features/club-detail/describe-error';
import { usePush } from '@/lib/use-push';
import { useCreateSubmission } from './use-support';

const TYPES = ['complaint', 'suggestion', 'comment'] as const;

function Label({ children }: { children: string }) {
  return (
    <FieldLabel>
      {children}
      <span className="text-red-500" aria-hidden="true">
        *
      </span>
    </FieldLabel>
  );
}

export function CreateSubmission() {
  const t = useTranslations('SUPPORT');
  const tErrors = useTranslations('ERRORS');
  const push = usePush();
  const create = useCreateSubmission();
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<CreateSubmissionForm>({ resolver: zodResolver(createSubmissionForm), defaultValues: { type: 'suggestion', title: '', body: '' }, mode: 'onTouched' });
  const busy = create.isPending || create.isSuccess;
  const message = (key?: string) => (key ? t(key.replace(/^SUPPORT\./, '')) : null);

  const submit = (values: CreateSubmissionForm) =>
    create.mutate({ type: values.type, title: values.title.trim(), body: values.body.trim() }, { onSuccess: () => push('/support') });

  return (
    <section className="min-h-screen flex items-center justify-center p-4">
      <div className="w-full max-w-lg">
        <header className="text-center mb-8">
          <p className="font-display text-3xl font-bold text-gray-900 dark:text-white">💬 {t('title')}</p>
          <p className="text-gray-500 dark:text-gray-400 mt-2">{t('create_subtitle')}</p>
        </header>
        <article className="bg-white dark:bg-gray-900 rounded-2xl shadow-xl p-8">
          <h1 className="text-xl font-semibold text-gray-900 dark:text-white mb-6">{t('create_title')}</h1>
          <form onSubmit={handleSubmit(submit)} className="space-y-5" noValidate>
            <Field>
              <Label>{t('type_label')}</Label>
              <FieldControl>
                <NativeSelect data-testid="submission-type-select" className="bg-white text-gray-900 dark:bg-gray-900 dark:text-white" {...register('type')}>
                  {TYPES.map((type) => (
                    <option key={type} value={type} className="bg-white text-gray-900 dark:bg-gray-900 dark:text-white">
                      {t(`type_${type}`)}
                    </option>
                  ))}
                </NativeSelect>
              </FieldControl>
            </Field>

            <Field invalid={!!errors.title}>
              <Label>{t('title_label')}</Label>
              <FieldControl>
                <Input type="text" data-testid="submission-title-input" placeholder={t('title_placeholder')} {...register('title')} />
              </FieldControl>
              <FieldError>{message(errors.title?.message)}</FieldError>
            </Field>

            <Field invalid={!!errors.body}>
              <Label>{t('body_label')}</Label>
              <FieldControl>
                <Textarea rows={5} className="resize-none" data-testid="submission-body-input" placeholder={t('body_placeholder')} {...register('body')} />
              </FieldControl>
              <FieldError>{message(errors.body?.message)}</FieldError>
            </Field>

            {create.isError && (
              <div role="alert" className="flex items-start gap-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-400">
                <span className="mt-0.5 shrink-0" aria-hidden="true">
                  ⚠️
                </span>
                <span>{describeError(create.error, tErrors)}</span>
              </div>
            )}

            <div className="flex gap-3 pt-2">
              <Button type="button" variant="outline" onClick={() => push('/support')} className="flex-1">
                {t('cancel')}
              </Button>
              <Button type="submit" disabled={busy} data-testid="submission-submit" className="flex-1 bg-primary-600 hover:bg-primary-700 text-white">
                {busy ? (
                  <>
                    <Spinner className="mr-2" />
                    {t('submitting')}
                  </>
                ) : (
                  t('submit')
                )}
              </Button>
            </div>
          </form>
        </article>
      </div>
    </section>
  );
}

// src/app/features/support/create-submission/create-submission.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { TranslatePipe } from '@ngx-translate/core';
import { SupportService } from '../../../core/services/support.service';
import { SeoService } from '../../../core/services/seo.service';
import { SubmissionType } from '../../../core/models/support.model';
import { HlmFieldImports } from '../../../shared/spartan/field/src';
import { HlmInput } from '../../../shared/spartan/input/src';
import { HlmButton } from '../../../shared/spartan/button/src';
import { HlmSpinner } from '../../../shared/spartan/spinner/src';

interface CreateSubmissionForm {
  type: FormControl<SubmissionType>;
  title: FormControl<string>;
  body: FormControl<string>;
}

@Component({
  selector: 'app-create-submission',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, TranslatePipe, ...HlmFieldImports, HlmInput, HlmButton, HlmSpinner],
  templateUrl: './create-submission.component.html',
})
export class CreateSubmissionComponent {
  private readonly support = inject(SupportService);
  private readonly router = inject(Router);
  private readonly seo = inject(SeoService);

  readonly types: SubmissionType[] = ['complaint', 'suggestion', 'comment'];

  private readonly _errorMessage = signal<string | null>(null);
  readonly errorMessage = this._errorMessage.asReadonly();

  private readonly _isSubmitting = signal(false);
  readonly isSubmitting = this._isSubmitting.asReadonly();

  readonly form = new FormGroup<CreateSubmissionForm>({
    type: new FormControl<SubmissionType>('suggestion', { nonNullable: true, validators: [Validators.required] }),
    title: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(3), Validators.maxLength(120)],
    }),
    body: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(10), Validators.maxLength(2000)],
    }),
  });

  constructor() {
    this.seo.setPageI18n('SUPPORT.create_title');
  }

  cancel(): void {
    this.router.navigate(['/support']).catch(() => { /* */ });
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this._isSubmitting.set(true);
    this._errorMessage.set(null);

    const { type, title, body } = this.form.getRawValue();

    try {
      await this.support.submit({ type, title: title.trim(), body: body.trim() });
      await this.router.navigate(['/support']);
    } catch (err) {
      this._errorMessage.set(err instanceof Error ? err.message : 'Failed to submit');
    } finally {
      this._isSubmitting.set(false);
    }
  }
}

<section class="min-h-screen flex items-center justify-center p-4">
  <div class="w-full max-w-lg">

    <header class="text-center mb-8">
      <p class="font-display text-3xl font-bold text-gray-900 dark:text-white">💬 {{ 'SUPPORT.title' | translate }}</p>
      <p class="text-gray-500 dark:text-gray-400 mt-2">{{ 'SUPPORT.create_subtitle' | translate }}</p>
    </header>

    <article class="bg-white dark:bg-gray-900 rounded-2xl shadow-xl p-8">
      <h1 class="text-xl font-semibold text-gray-900 dark:text-white mb-6">{{ 'SUPPORT.create_title' | translate }}</h1>

      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-5" novalidate>

        <!-- Type -->
        <hlm-field>
          <label hlmFieldLabel for="submission-type">
            {{ 'SUPPORT.type_label' | translate }}
            <span class="text-red-500" aria-hidden="true">*</span>
          </label>
          <select
            hlmInput
            id="submission-type"
            formControlName="type"
            class="w-full bg-white text-gray-900 dark:bg-gray-900 dark:text-white"
            data-testid="submission-type-select"
          >
            @for (type of types; track type) {
              <option [value]="type" class="bg-white text-gray-900 dark:bg-gray-900 dark:text-white">{{ 'SUPPORT.type_' + type | translate }}</option>
            }
          </select>
        </hlm-field>

        <!-- Title -->
        <hlm-field>
          <label hlmFieldLabel for="submission-title">
            {{ 'SUPPORT.title_label' | translate }}
            <span class="text-red-500" aria-hidden="true">*</span>
          </label>
          <input
            hlmInput
            id="submission-title"
            type="text"
            formControlName="title"
            class="w-full"
            data-testid="submission-title-input"
            [placeholder]="'SUPPORT.title_placeholder' | translate"
          />
          <hlm-field-error validator="required">{{ 'SUPPORT.title_required' | translate }}</hlm-field-error>
          <hlm-field-error validator="minlength">{{ 'SUPPORT.title_min' | translate }}</hlm-field-error>
          <hlm-field-error validator="maxlength">{{ 'SUPPORT.title_max' | translate }}</hlm-field-error>
        </hlm-field>

        <!-- Body -->
        <hlm-field>
          <label hlmFieldLabel for="submission-body">
            {{ 'SUPPORT.body_label' | translate }}
            <span class="text-red-500" aria-hidden="true">*</span>
          </label>
          <textarea
            hlmInput
            id="submission-body"
            formControlName="body"
            rows="5"
            class="w-full resize-none"
            data-testid="submission-body-input"
            [placeholder]="'SUPPORT.body_placeholder' | translate"
          ></textarea>
          <hlm-field-error validator="required">{{ 'SUPPORT.body_required' | translate }}</hlm-field-error>
          <hlm-field-error validator="minlength">{{ 'SUPPORT.body_min' | translate }}</hlm-field-error>
          <hlm-field-error validator="maxlength">{{ 'SUPPORT.body_max' | translate }}</hlm-field-error>
        </hlm-field>

        <!-- Error alert -->
        @if (errorMessage()) {
          <div class="flex items-start gap-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-400"
               role="alert">
            <span class="mt-0.5 shrink-0" aria-hidden="true">⚠️</span>
            <span>{{ errorMessage() }}</span>
          </div>
        }

        <!-- Actions -->
        <div class="flex gap-3 pt-2">
          <button hlmBtn type="button" variant="outline" (click)="cancel()" class="flex-1">
            {{ 'SUPPORT.cancel' | translate }}
          </button>
          <button hlmBtn type="submit" [disabled]="isSubmitting()"
                  data-testid="submission-submit"
                  class="flex-1 bg-primary-600 hover:bg-primary-700 text-white">
            @if (isSubmitting()) {
              <hlm-spinner class="mr-2" />
              {{ 'SUPPORT.submitting' | translate }}
            } @else {
              {{ 'SUPPORT.submit' | translate }}
            }
          </button>
        </div>

      </form>
    </article>
  </div>
</section>
