// apps/web/src/features/organizer/create-club.tsx
'use client';
'use no memo';

import { zodResolver } from '@hookform/resolvers/zod';
import { createClubForm, type CreateClubForm } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import { useEffect, useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { FormField } from '@/components/form-field';
import { Button } from '@/components/ui/button';
import { Field, FieldControl, FieldError, FieldLabel } from '@/components/ui/field';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import { describeError } from '@/features/club-detail/describe-error';
import { useMyClubs } from '@/features/clubs/use-clubs';
import { useSession } from '@/features/clubs/use-session';
import { usePush } from '@/lib/use-push';
import { ErrorAlert, FormCard, VisibilitySwitch } from './club-form-parts';
import { CoverPreview } from './cover-preview';
import { useCreateClub } from './use-organizer';

const DEFAULTS: CreateClubForm = { name: '', description: '', isPublic: true, city: '', coverUrl: '', firstEventTitle: '', firstEventDate: '', firstEventCity: '' };

export function CreateClub() {
  const t = useTranslations('CREATE_CLUB');
  const tAll = useTranslations();
  const tErrors = useTranslations('ERRORS');
  const push = usePush();
  const { user } = useSession();
  const mine = useMyClubs(user !== null);
  const create = useCreateClub();
  const [showFirstEvent, setShowFirstEvent] = useState(false);
  const [created, setCreated] = useState(false);
  const {
    register,
    handleSubmit,
    setValue,
    control,
    formState: { errors },
  } = useForm<CreateClubForm>({ resolver: zodResolver(createClubForm), defaultValues: DEFAULTS, mode: 'onTouched' });
  const [isPublic, coverUrl] = useWatch({ control, name: ['isPublic', 'coverUrl'] });

  // one club per organizer: whoever already owns one is sent back to the list (not after creating it, which lands on the new club)
  const ownsClub = user !== null && !created && (mine.data?.some((c) => c.organizerId === user.id) ?? false);
  useEffect(() => {
    if (ownsClub) push('/clubs');
  }, [ownsClub, push]);

  const submit = async (values: CreateClubForm) => {
    if (create.isPending) return;
    const eventTitle = values.firstEventTitle.trim();
    const eventCity = values.firstEventCity.trim();
    const withEvent = showFirstEvent && eventTitle !== '' && values.firstEventDate !== '' && eventCity !== '';
    try {
      const club = await create.mutateAsync({
        club: { name: values.name, description: values.description, isPublic: values.isPublic, city: values.city, coverUrl: values.coverUrl || null },
        firstEvent: withEvent ? { title: eventTitle, date: new Date(values.firstEventDate).toISOString(), city: eventCity } : null,
      });
      setCreated(true);
      push(`/clubs/${club.id}`);
    } catch {
      // surfaced through create.error
    }
  };

  return (
    <FormCard subtitle={t('subtitle')} title={t('title')}>
      <form onSubmit={handleSubmit(submit)} className="space-y-5" noValidate>
        <FormField
          id="club-name"
          type="text"
          data-testid="club-name-input"
          label={
            <>
              {t('name_label')}
              <span className="text-red-500" aria-hidden="true">
                *
              </span>
            </>
          }
          placeholder={t('name_placeholder')}
          error={errors.name?.message}
          {...register('name')}
        />

        <Field invalid={!!errors.description}>
          <FieldLabel className="text-sm font-medium text-gray-700 dark:text-gray-300">{t('description_label')}</FieldLabel>
          <FieldControl>
            <Textarea rows={3} className="resize-none" placeholder={t('description_placeholder')} {...register('description')} />
          </FieldControl>
          <FieldError className="text-xs">{errors.description?.message ? tAll(errors.description.message) : null}</FieldError>
        </Field>

        <div>
          <CoverPreview src={coverUrl} />
          <FormField id="club-cover-url" type="url" label={t('cover_url_label')} placeholder={t('cover_url_placeholder')} error={errors.coverUrl?.message} {...register('coverUrl')} />
          {errors.coverUrl ? null : <p className="mt-1 text-xs text-gray-400 dark:text-gray-500">{t('cover_url_hint')}</p>}
        </div>

        <VisibilitySwitch
          legend={t('visibility_legend')}
          label={t('public_label')}
          description={t('public_desc')}
          checked={isPublic}
          onChange={(next) => setValue('isPublic', next)}
        />

        <div className="space-y-3">
          <Button type="button" variant="ghost" onClick={() => setShowFirstEvent((v) => !v)}>
            {showFirstEvent ? t('remove_first_meeting') : t('add_first_meeting')}
          </Button>
          {showFirstEvent ? (
            <>
              <FormField id="event-title" type="text" label={t('first_meeting_title_label')} placeholder={t('first_meeting_title_placeholder')} {...register('firstEventTitle')} />
              <FormField id="event-date" type="datetime-local" label={t('first_meeting_date_label')} {...register('firstEventDate')} />
              <FormField id="event-city" type="text" label={t('first_meeting_city_label')} placeholder={t('first_meeting_city_placeholder')} {...register('firstEventCity')} />
            </>
          ) : null}
        </div>

        {create.isError ? <ErrorAlert>{describeError(create.error, tErrors)}</ErrorAlert> : null}

        <div className="flex gap-3 pt-2">
          <Button type="button" variant="outline" onClick={() => push('/clubs')} className="flex-1">
            {t('cancel')}
          </Button>
          <Button type="submit" disabled={create.isPending} data-testid="club-submit" className="flex-1 bg-primary-600 hover:bg-primary-700 text-white">
            {create.isPending ? (
              <>
                <Spinner className="mr-2" />
                {t('submitting')}
              </>
            ) : (
              t('submit')
            )}
          </Button>
        </div>
      </form>
    </FormCard>
  );
}

// src/app/features/clubs/create-club/create-club.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  signal,
} from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ClubService } from '../../../core/services/club.service';
import { AuthService } from '../../../core/auth/auth.service';

interface CreateClubForm {
  name: FormControl<string>;
  description: FormControl<string>;
  isPublic: FormControl<boolean>;
}

@Component({
  selector: 'app-create-club',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule],
  templateUrl: './create-club.component.html',
})
export class CreateClubComponent {
  private readonly clubService = inject(ClubService);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly errorMessage = signal<string | null>(null);
  readonly isSubmitting = signal(false);

  readonly form = new FormGroup<CreateClubForm>({
    name: new FormControl('', {
      nonNullable: true,
      validators: [Validators.required, Validators.minLength(3), Validators.maxLength(100)],
    }),
    description: new FormControl('', {
      nonNullable: true,
      validators: [Validators.maxLength(500)],
    }),
    isPublic: new FormControl(true, { nonNullable: true }),
  });

  togglePublic(): void {
    const current = this.form.controls.isPublic.value;
    this.form.controls.isPublic.setValue(!current);
  }

  cancel(): void {
    this.router.navigate(['/clubs']);
  }

  async onSubmit(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.isSubmitting.set(true);
    this.errorMessage.set(null);

    const { name, description, isPublic } = this.form.getRawValue();

    try {
      const club = await this.clubService.createClub({ name, description, isPublic });
      this.router.navigate(['/clubs', club.id]);
    } catch (err) {
      this.errorMessage.set(err instanceof Error ? err.message : 'Failed to create club');
    } finally {
      this.isSubmitting.set(false);
    }
  }
}

<section class="min-h-screen flex items-center justify-center p-4">
  <div class="w-full max-w-lg">

    <header class="text-center mb-8">
      <h1 class="font-display text-3xl font-bold text-gray-900 dark:text-white">📚 BookClub</h1>
      <p class="text-gray-500 dark:text-gray-400 mt-2">{{ 'CREATE_CLUB.subtitle' | translate }}</p>
    </header>

    <article class="bg-white dark:bg-gray-900 rounded-2xl shadow-xl p-8">
      <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-6">{{ 'CREATE_CLUB.title' | translate }}</h2>

      <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-5" novalidate>

        <!-- Name -->
        <hlm-field>
          <label hlmFieldLabel for="club-name">
            {{ 'CREATE_CLUB.name_label' | translate }}
            <span class="text-red-500" aria-hidden="true">*</span>
          </label>
          <input
            hlmInput
            id="club-name"
            type="text"
            formControlName="name"
            class="w-full"
            data-testid="club-name-input"
            [placeholder]="'CREATE_CLUB.name_placeholder' | translate"
          />
          <hlm-field-error validator="required">{{ 'CREATE_CLUB.name_required' | translate }}</hlm-field-error>
          <hlm-field-error validator="minlength">{{ 'CREATE_CLUB.name_min' | translate }}</hlm-field-error>
          <hlm-field-error validator="maxlength">{{ 'CREATE_CLUB.name_max' | translate }}</hlm-field-error>
        </hlm-field>

        <!-- Description -->
        <hlm-field>
          <label hlmFieldLabel for="club-description">{{ 'CREATE_CLUB.description_label' | translate }}</label>
          <textarea
            hlmInput
            id="club-description"
            formControlName="description"
            rows="3"
            class="w-full resize-none"
            [placeholder]="'CREATE_CLUB.description_placeholder' | translate"
          ></textarea>
          <hlm-field-error validator="maxlength">{{ 'CREATE_CLUB.description_max' | translate }}</hlm-field-error>
        </hlm-field>

        <!-- Cover image URL -->
        <div>
          <label for="club-cover-url" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ 'CREATE_CLUB.cover_url_label' | translate }}
          </label>
          @if (form.controls.coverUrl.value) {
            <div class="relative mb-2 rounded-xl overflow-hidden h-28 bg-gray-100 dark:bg-gray-700">
              <img
                [ngSrc]="form.controls.coverUrl.value"
                fill
                sizes="500px"
                alt="Cover preview"
                class="object-cover"
                (error)="form.controls.coverUrl.setValue('')"
              />
            </div>
          }
          <input
            hlmInput
            id="club-cover-url"
            type="url"
            formControlName="coverUrl"
            class="w-full"
            [placeholder]="'CREATE_CLUB.cover_url_placeholder' | translate"
          />
          @if (form.controls.coverUrl.touched && form.controls.coverUrl.errors?.['pattern']) {
            <p class="mt-1 text-xs text-red-600 dark:text-red-400" role="alert">{{ 'CREATE_CLUB.cover_url_invalid' | translate }}</p>
          } @else {
            <p class="mt-1 text-xs text-gray-400 dark:text-gray-500">{{ 'CREATE_CLUB.cover_url_hint' | translate }}</p>
          }
        </div>

        <!-- Visibility toggle -->
        <fieldset>
          <legend class="text-sm font-semibold text-gray-900 dark:text-white mb-3">{{ 'CREATE_CLUB.visibility_legend' | translate }}</legend>
          <div class="flex items-center justify-between rounded-xl bg-gray-50 dark:bg-gray-800 px-4 py-3">
            <div>
              <p class="text-sm font-medium text-gray-700 dark:text-gray-300">{{ 'CREATE_CLUB.public_label' | translate }}</p>
              <p class="text-xs text-gray-500 dark:text-gray-400 mt-0.5">{{ 'CREATE_CLUB.public_desc' | translate }}</p>
            </div>
            <button
              type="button"
              role="switch"
              [attr.aria-checked]="form.controls.isPublic.value"
              (click)="togglePublic()"
              class="relative inline-flex h-6 w-11 items-center rounded-full transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2"
              [class.bg-primary-600]="form.controls.isPublic.value"
              [class.bg-gray-300]="!form.controls.isPublic.value"
              [class.dark:bg-gray-600]="!form.controls.isPublic.value"
            >
              <span
                class="inline-block h-4 w-4 transform rounded-full bg-white shadow-sm transition-transform duration-200"
                [class.translate-x-6]="form.controls.isPublic.value"
                [class.translate-x-1]="!form.controls.isPublic.value"
              ></span>
            </button>
          </div>
        </fieldset>

        <!-- First meeting toggle -->
        <div class="space-y-3">
          <button type="button" hlmBtn variant="ghost" (click)="toggleFirstEvent()">
            {{ (showFirstEvent() ? 'CREATE_CLUB.remove_first_meeting' : 'CREATE_CLUB.add_first_meeting') | translate }}
          </button>

          @if (showFirstEvent()) {
            <hlm-field>
              <label hlmFieldLabel for="event-title">{{ 'CREATE_CLUB.first_meeting_title_label' | translate }}</label>
              <input
                hlmInput
                id="event-title"
                type="text"
                [formControl]="eventTitleCtrl"
                class="w-full"
                [placeholder]="'CREATE_CLUB.first_meeting_title_placeholder' | translate"
              />
            </hlm-field>

            <hlm-field>
              <label hlmFieldLabel for="event-date">{{ 'CREATE_CLUB.first_meeting_date_label' | translate }}</label>
              <input
                hlmInput
                id="event-date"
                type="datetime-local"
                [formControl]="eventDateCtrl"
                class="w-full"
              />
            </hlm-field>

            <hlm-field>
              <label hlmFieldLabel for="event-city">{{ 'CREATE_CLUB.first_meeting_city_label' | translate }}</label>
              <input
                hlmInput
                id="event-city"
                type="text"
                [formControl]="eventCityCtrl"
                class="w-full"
                [placeholder]="'CREATE_CLUB.first_meeting_city_placeholder' | translate"
              />
            </hlm-field>
          }
        </div>

        <!-- Error alert -->
        @if (errorMessage()) {
          <div class="flex items-start gap-2 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 px-4 py-3 text-sm text-red-700 dark:text-red-400"
               role="alert">
            <span class="mt-0.5 shrink-0" aria-hidden="true">⚠️</span>
            <span>{{ errorMessage() }}</span>
          </div>
        }

        <!-- Actions -->
        <div class="flex gap-3 pt-2">
          <button hlmBtn type="button" variant="outline" (click)="cancel()" class="flex-1">
            {{ 'CREATE_CLUB.cancel' | translate }}
          </button>
          <button hlmBtn type="submit" [disabled]="isSubmitting()"
                  class="flex-1 bg-primary-600 hover:bg-primary-700 text-white">
            @if (isSubmitting()) {
              <hlm-spinner class="mr-2" />
              {{ 'CREATE_CLUB.submitting' | translate }}
            } @else {
              {{ 'CREATE_CLUB.submit' | translate }}
            }
          </button>
        </div>

      </form>
    </article>
  </div>
</section>
