// apps/web/src/components/layout/footer.tsx
import { getTranslations } from 'next-intl/server';
import { AppLink } from '@/components/app-link';

const LINK =
  'text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 rounded';

export async function Footer() {
  const t = await getTranslations('FOOTER');
  return (
    <footer className="bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 py-6" role="contentinfo">
      <div className="max-w-6xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
        <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">
          📚 BookClub &copy; {new Date().getFullYear()} — {t('rights')}
        </p>
        <nav aria-label="Footer navigation">
          <ul className="flex items-center gap-4">
            <li>
              <AppLink href="/privacy" className={LINK}>
                {t('privacy')}
              </AppLink>
            </li>
            <li>
              <AppLink href="/terms" className={LINK}>
                {t('terms')}
              </AppLink>
            </li>
          </ul>
        </nav>
      </div>
    </footer>
  );
}

// src/app/layout/footer/footer.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <footer
      class="bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 py-6"
      role="contentinfo"
    >
      <div class="max-w-6xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
        <!-- Brand -->
        <p class="text-sm text-gray-500 dark:text-gray-400 font-medium">
          📚 BookClub &copy; {{ year }}
        </p>

        <!-- Links -->
        <nav aria-label="Footer navigation" class="flex items-center gap-4">
          <a
            routerLink="/privacy"
            class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white
                   transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500
                   focus:ring-offset-2 rounded"
          >
            Privacy
          </a>
          <a
            routerLink="/terms"
            class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white
                   transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500
                   focus:ring-offset-2 rounded"
          >
            Terms
          </a>
        </nav>
      </div>
    </footer>
  `,
})
export class FooterComponent {
  readonly year = new Date().getFullYear();
}

<footer
      class="bg-gray-50 dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 py-6"
      role="contentinfo"
    >
      <div class="max-w-6xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-3">
        <!-- Brand -->
        <p class="text-sm text-gray-500 dark:text-gray-400 font-medium">
          📚 BookClub &copy; {{ year }} — {{ 'FOOTER.rights' | translate }}
        </p>

        <!-- Links -->
        <nav aria-label="Footer navigation">
          <ul class="flex items-center gap-4">
            <li>
              <a
                routerLink="/privacy"
                class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white
                       transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500
                       focus:ring-offset-2 rounded"
              >
                {{ 'FOOTER.privacy' | translate }}
              </a>
            </li>
            <li>
              <a
                routerLink="/terms"
                class="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white
                       transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500
                       focus:ring-offset-2 rounded"
              >
                {{ 'FOOTER.terms' | translate }}
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </footer>
