// apps/web/src/components/social-badges.tsx
import type { UserSocials } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import { cn } from '@/lib/utils';
import { SOCIAL_ICON_PATHS } from './social-icon-paths';

type Key = keyof typeof SOCIAL_ICON_PATHS;

interface Network {
  key: Key;
  name: string;
  base: string;
  /** the value may be a full URL instead of a handle */
  acceptsUrl?: boolean;
  /** shown as @handle; otherwise `text` or the raw value */
  at?: boolean;
  text?: string;
  link: string;
  iconClass?: string;
}

const FOCUS = 'transition-colors duration-150 outline-none focus-visible:ring-2 focus-visible:ring-offset-2';

const NETWORKS: readonly Network[] = [
  { key: 'telegram', name: 'Telegram', base: 'https://t.me/', at: true, link: `border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 hover:bg-blue-100 dark:hover:bg-blue-900/50 focus-visible:ring-blue-500 ${FOCUS}` },
  { key: 'instagram', name: 'Instagram', base: 'https://instagram.com/', at: true, iconClass: 'text-pink-600', link: 'border-pink-200 dark:border-pink-800 bg-pink-50 dark:bg-pink-900/30 bg-clip-text bg-gradient-to-r from-pink-600 via-purple-600 to-orange-500 text-transparent hover:opacity-80 transition-opacity duration-150 outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-pink-500' },
  { key: 'twitter', name: 'Twitter / X', base: 'https://x.com/', at: true, link: `border-gray-300 dark:border-gray-600 bg-gray-900 dark:bg-gray-950 text-white hover:bg-gray-700 dark:hover:bg-gray-800 focus-visible:ring-gray-500 ${FOCUS}` },
  { key: 'linkedin', name: 'LinkedIn', base: 'https://linkedin.com/in/', acceptsUrl: true, text: 'LinkedIn', link: `border-blue-300 dark:border-blue-700 bg-blue-600 dark:bg-blue-700 text-white hover:bg-blue-700 dark:hover:bg-blue-600 focus-visible:ring-blue-500 ${FOCUS}` },
  { key: 'github', name: 'GitHub', base: 'https://github.com/', link: `border-gray-300 dark:border-gray-600 bg-gray-800 dark:bg-gray-900 text-gray-100 hover:bg-gray-700 dark:hover:bg-gray-800 focus-visible:ring-gray-500 ${FOCUS}` },
  { key: 'goodreads', name: 'Goodreads', base: 'https://goodreads.com/', acceptsUrl: true, text: 'Goodreads', link: `border-amber-300 dark:border-amber-700 bg-amber-50 dark:bg-amber-900/30 text-amber-800 dark:text-amber-300 hover:bg-amber-100 dark:hover:bg-amber-900/50 focus-visible:ring-amber-500 ${FOCUS}` },
];

const ABSOLUTE = /^https?:\/\//i;

export function SocialBadges({ socials }: { socials: UserSocials }) {
  const t = useTranslations('PROFILE');
  return (
    <ul className="flex flex-wrap gap-2 list-none p-0 m-0" aria-label={t('socials_title')}>
      {NETWORKS.map((n) => {
        const value = socials[n.key];
        if (!value) return null;
        const href = n.acceptsUrl && ABSOLUTE.test(value) ? value : `${n.base}${value}`;
        const handle = n.at ? `@${value}` : value;
        return (
          <li key={n.key}>
            <a
              href={href}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={`${n.name}: ${n.at ? handle : value}`}
              className={cn('inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-medium', n.link)}
            >
              <svg className={cn('h-3.5 w-3.5 shrink-0', n.iconClass)} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                <path d={SOCIAL_ICON_PATHS[n.key]} />
              </svg>
              {n.text ?? handle}
            </a>
          </li>
        );
      })}
    </ul>
  );
}

// src/app/shared/components/social-badges/social-badges.component.ts
import { Component, ChangeDetectionStrategy, input } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { UserSocials } from '../../../core/models/user.model';

@Component({
  selector: 'app-social-badges',
  standalone: true,
  imports: [TranslatePipe],
  templateUrl: './social-badges.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SocialBadgesComponent {
  readonly socials = input.required<UserSocials>();
}

<ul class="flex flex-wrap gap-2 list-none p-0 m-0" [attr.aria-label]="'PROFILE.socials_title' | translate">

  @if (socials().telegram) {
    <li>
      <a
        [href]="'https://t.me/' + socials().telegram"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-blue-200
               dark:border-blue-800 bg-blue-50 dark:bg-blue-900/30 px-3 py-1.5
               text-xs font-medium text-blue-700 dark:text-blue-300
               hover:bg-blue-100 dark:hover:bg-blue-900/50
               transition-colors duration-150 focus:outline-none focus:ring-2
               focus:ring-blue-500 focus:ring-offset-2"
        [attr.aria-label]="'Telegram: @' + socials().telegram"
      >
        <svg class="h-3.5 w-3.5 shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.894 8.221-1.97 9.28c-.145.658-.537.818-1.084.508l-3-2.21-1.447 1.394c-.16.16-.295.295-.605.295l.213-3.053 5.56-5.023c.242-.213-.054-.333-.373-.12l-6.871 4.326-2.962-.924c-.643-.204-.657-.643.136-.953l11.57-4.461c.537-.194 1.006.131.833.941z"/>
        </svg>
        &#64;{{ socials().telegram }}
      </a>
    </li>
  }

  @if (socials().instagram) {
    <li>
      <a
        [href]="'https://instagram.com/' + socials().instagram"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-pink-200
               dark:border-pink-800 bg-pink-50 dark:bg-pink-900/30 px-3 py-1.5
               text-xs font-medium bg-clip-text
               bg-gradient-to-r from-pink-600 via-purple-600 to-orange-500
               text-transparent hover:opacity-80
               transition-opacity duration-150 focus:outline-none focus:ring-2
               focus:ring-pink-500 focus:ring-offset-2"
        [attr.aria-label]="'Instagram: @' + socials().instagram"
      >
        <svg class="h-3.5 w-3.5 shrink-0 text-pink-600" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98C8.333 23.986 8.741 24 12 24c3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z"/>
        </svg>
        &#64;{{ socials().instagram }}
      </a>
    </li>
  }

  @if (socials().twitter) {
    <li>
      <a
        [href]="'https://x.com/' + socials().twitter"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-gray-300
               dark:border-gray-600 bg-gray-900 dark:bg-gray-950 px-3 py-1.5
               text-xs font-medium text-white
               hover:bg-gray-700 dark:hover:bg-gray-800
               transition-colors duration-150 focus:outline-none focus:ring-2
               focus:ring-gray-500 focus:ring-offset-2"
        [attr.aria-label]="'Twitter / X: @' + socials().twitter"
      >
        <svg class="h-3.5 w-3.5 shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
        </svg>
        &#64;{{ socials().twitter }}
      </a>
    </li>
  }

  @if (socials().linkedin) {
    <li>
      <a
        [href]="socials().linkedin!.startsWith('http')
          ? socials().linkedin!
          : 'https://linkedin.com/in/' + socials().linkedin"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-blue-300
               dark:border-blue-700 bg-blue-600 dark:bg-blue-700 px-3 py-1.5
               text-xs font-medium text-white
               hover:bg-blue-700 dark:hover:bg-blue-600
               transition-colors duration-150 focus:outline-none focus:ring-2
               focus:ring-blue-500 focus:ring-offset-2"
        [attr.aria-label]="'LinkedIn: ' + socials().linkedin"
      >
        <svg class="h-3.5 w-3.5 shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 23.2 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
        </svg>
        LinkedIn
      </a>
    </li>
  }

  @if (socials().github) {
    <li>
      <a
        [href]="'https://github.com/' + socials().github"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-gray-300
               dark:border-gray-600 bg-gray-800 dark:bg-gray-900 px-3 py-1.5
               text-xs font-medium text-gray-100
               hover:bg-gray-700 dark:hover:bg-gray-800
               transition-colors duration-150 focus:outline-none focus:ring-2
               focus:ring-gray-500 focus:ring-offset-2"
        [attr.aria-label]="'GitHub: ' + socials().github"
      >
        <svg class="h-3.5 w-3.5 shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0 1 12 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z"/>
        </svg>
        {{ socials().github }}
      </a>
    </li>
  }

  @if (socials().goodreads) {
    <li>
      <a
        [href]="socials().goodreads!.startsWith('http')
          ? socials().goodreads!
          : 'https://goodreads.com/' + socials().goodreads"
        target="_blank"
        rel="noopener noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-amber-300
               dark:border-amber-700 bg-amber-50 dark:bg-amber-900/30 px-3 py-1.5
               text-xs font-medium text-amber-800 dark:text-amber-300
               hover:bg-amber-100 dark:hover:bg-amber-900/50
               transition-colors duration-150 focus:outline-none focus:ring-2
               focus:ring-amber-500 focus:ring-offset-2"
        [attr.aria-label]="'Goodreads: ' + socials().goodreads"
      >
        <svg class="h-3.5 w-3.5 shrink-0" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
          <path d="M19.525 15.977V.49h-2.059v2.906h-.064a5.015 5.015 0 0 0-1.949-2.406C14.548.316 13.441 0 12.192 0c-1.648 0-3.037.434-4.175 1.303-1.136.869-1.927 2.045-2.373 3.527S5.07 7.857 5.07 9.481c0 1.624.188 3.069.562 4.337.374 1.268 1.004 2.326 1.889 3.172.885.847 2.056 1.271 3.512 1.271 1.248 0 2.35-.304 3.303-.911a4.961 4.961 0 0 0 1.999-2.456h.063v2.904c0 1.547-.272 2.806-.816 3.777-.544.971-1.33 1.666-2.359 2.085-1.029.419-2.264.628-3.703.628-.802 0-1.608-.1-2.416-.302a9.11 9.11 0 0 1-2.258-.961l-.88 1.674c.737.481 1.607.852 2.613 1.114 1.006.262 2.03.393 3.073.393 2.267 0 4.092-.411 5.469-1.231 1.377-.82 2.357-1.913 2.937-3.277.581-1.364.871-2.891.871-4.582zm-7.301-.34c-1.161 0-2.124-.31-2.888-.932-.764-.621-1.323-1.479-1.677-2.574-.354-1.095-.531-2.301-.531-3.617 0-2.006.401-3.62 1.203-4.845.802-1.225 2.04-1.837 3.717-1.837 1.677 0 2.908.609 3.691 1.827.783 1.218 1.176 2.855 1.176 4.913 0 1.296-.173 2.491-.519 3.581-.346 1.09-.895 1.955-1.649 2.591-.754.637-1.71.953-2.862.953-.001 0 .002-.06.339-.06z"/>
        </svg>
        Goodreads
      </a>
    </li>
  }

</ul>
