// src/app/shared/components/event-map/event-map.component.ts
import {
  Component, ChangeDetectionStrategy, input, signal, computed, inject, effect,
} from '@angular/core';
import { GoogleMap, MapAdvancedMarker, MapPolyline } from '@angular/google-maps';
import { TranslateModule } from '@ngx-translate/core';
import { of, switchMap, catchError, take } from 'rxjs';
import { AfterMeetingVenue } from '../../../core/models/event.model';
import { MapsConfigService } from '../../../core/services/maps-config.service';
import { GeocodingService } from '../../../core/services/geocoding.service';

@Component({
  selector: 'app-event-map',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [GoogleMap, MapAdvancedMarker, MapPolyline, TranslateModule],
  templateUrl: './event-map.component.html',
})
export class EventMapComponent {
  readonly lat = input.required<number | null>();
  readonly lng = input.required<number | null>();
  readonly address = input<string | null>(null);
  readonly afterMeetingVenue = input<AfterMeetingVenue | null>(null);

  private readonly maps = inject(MapsConfigService);
  private readonly geocoding = inject(GeocodingService);
  private readonly nativeMap = signal<google.maps.Map | null>(null);

  readonly isReady = computed(() => this.maps.isLoaded() && this.lat() != null && this.lng() != null);
  readonly center = computed<google.maps.LatLngLiteral>(() => ({ lat: this.lat() ?? 0, lng: this.lng() ?? 0 }));
  readonly afterVenuePos = computed<google.maps.LatLngLiteral | null>(() => {
    const v = this.afterMeetingVenue();
    return v?.lat != null && v?.lng != null ? { lat: v.lat, lng: v.lng } : null;
  });
  readonly mapsUrl = computed(() => `https://www.google.com/maps?q=${this.lat()},${this.lng()}`);
  readonly mapOptions = computed<google.maps.MapOptions>(() => {
    const mapId = this.maps.mapId();
    return {
      clickableIcons: false,
      gestureHandling: 'cooperative',
      ...(mapId ? { mapId } : {}),
    };
  });
  readonly resolvedAfterVenuePos = signal<google.maps.LatLngLiteral | null>(null);
  readonly polylinePath = computed<google.maps.LatLngLiteral[] | null>(() => {
    const after = this.resolvedAfterVenuePos();
    return after ? [this.center(), after] : null;
  });
  readonly polylineOptions: google.maps.PolylineOptions = {
    strokeColor: '#4f46e5', strokeWeight: 3, strokeOpacity: 0.7, geodesic: true,
  };

  onMapReady(map: google.maps.Map): void {
    this.nativeMap.set(map);
  }

  constructor() {
    effect(() => {
      const venue = this.afterMeetingVenue();
      if (venue?.lat != null && venue?.lng != null) {
        this.resolvedAfterVenuePos.set({ lat: venue.lat, lng: venue.lng });
        return;
      }
      if (!venue?.address || !this.isReady()) {
        this.resolvedAfterVenuePos.set(null);
        return;
      }
      this.geocoding.autocomplete$(venue.address, undefined, 1).pipe(
        take(1),
        switchMap(suggestions => {
          const s = suggestions[0];
          if (!s) return of(null);
          if (s.lat != null && s.lng != null) return of(s);
          if (s.place_id) return this.geocoding.getPlaceDetails(s.place_id).pipe(catchError(() => of(s)));
          return of(s);
        }),
      ).subscribe(s => {
        this.resolvedAfterVenuePos.set(
          s?.lat != null && s?.lng != null ? { lat: s.lat, lng: s.lng } : null,
        );
      });
    });

    effect(() => {
      const map = this.nativeMap();
      const afterPos = this.resolvedAfterVenuePos();
      if (!map || !afterPos) return;
      const bounds = new google.maps.LatLngBounds();
      bounds.extend(this.center());
      bounds.extend(afterPos);
      map.fitBounds(bounds, 60);
    });
  }
}

<div [hidden]="!isReady()" class="flex flex-col gap-3 mt-3">
  <google-map [center]="center()" [zoom]="15" [options]="mapOptions()" width="100%" height="300px" class="rounded-xl overflow-hidden block" (mapInitialized)="onMapReady($event)">
    <map-advanced-marker [position]="center()" [title]="address() ?? ''" />
    <map-advanced-marker [hidden]="!resolvedAfterVenuePos()" [position]="resolvedAfterVenuePos() ?? center()" [title]="afterMeetingVenue()?.name ?? ''" />
    @if (polylinePath()) {
      <map-polyline [path]="polylinePath()!" [options]="polylineOptions" />
    }
  </google-map>
  <a [href]="mapsUrl()" target="_blank" rel="noopener noreferrer"
     class="inline-flex items-center gap-1.5 text-sm text-accent-500 hover:underline self-start">
    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
      <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/>
    </svg>
    {{ 'EVENTS.open_in_maps' | translate }}
  </a>
</div>

// apps/web/src/features/events/event-map.tsx
'use client';

import type { AfterMeetingVenue } from '@book-club/contracts';
import { AdvancedMarker, APIProvider, Map, Polyline, useMap } from '@vis.gl/react-google-maps';
import { useTranslations } from 'next-intl';
import { useEffect } from 'react';
import { useMapsConfig, useVenuePosition, useWalkingRoute, type LatLng } from './use-venue';

// Google's documented placeholder id: advanced markers refuse to render on a map without one
const FALLBACK_MAP_ID = 'DEMO_MAP_ID';

function FitBounds({ points }: { points: readonly LatLng[] | null }) {
  const map = useMap();
  useEffect(() => {
    if (!map || !points || points.length < 2) return;
    const lats = points.map((p) => p.lat);
    const lngs = points.map((p) => p.lng);
    map.fitBounds({ north: Math.max(...lats), south: Math.min(...lats), east: Math.max(...lngs), west: Math.min(...lngs) }, 60);
  }, [map, points]);
  return null;
}

interface Props {
  lat: number;
  lng: number;
  address: string | null;
  afterMeetingVenue: AfterMeetingVenue | null;
}

/** Loaded lazily by the event page; renders nothing until the Maps key arrives (and for good if there is none). */
export default function EventMap({ lat, lng, address, afterMeetingVenue }: Props) {
  const t = useTranslations('EVENTS');
  const config = useMapsConfig();
  const center: LatLng = { lat, lng };
  const venue = useVenuePosition(config.data ? afterMeetingVenue : null);
  const route = useWalkingRoute(center, venue);

  if (!config.data) return null;
  return (
    <div className="flex flex-col gap-3 mt-3">
      <APIProvider apiKey={config.data.apiKey} version="weekly">
        <Map
          defaultCenter={center}
          defaultZoom={15}
          mapId={config.data.mapId || FALLBACK_MAP_ID}
          clickableIcons={false}
          gestureHandling="cooperative"
          style={{ width: '100%', height: 300 }}
          className="rounded-xl overflow-hidden block"
        >
          <AdvancedMarker position={center} title={address ?? ''} />
          {venue && <AdvancedMarker position={venue} title={afterMeetingVenue?.name ?? ''} />}
          {route && <Polyline path={route} strokeColor="#4f46e5" strokeWeight={4} strokeOpacity={0.8} />}
          <FitBounds points={venue ? (route ?? [center, venue]) : null} />
        </Map>
      </APIProvider>
      <a
        href={`https://www.google.com/maps?q=${lat},${lng}`}
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1.5 text-sm text-accent-500 hover:underline self-start"
      >
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z" />
        </svg>
        {t('open_in_maps')}
      </a>
    </div>
  );
}
