// src/app/features/clubs/club-detail/book-vote/book-vote-section.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  signal,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { rxResource } from '@angular/core/rxjs-interop';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { toast } from '@spartan-ng/brain/sonner';
import { BookVoteService } from '../../../../core/services/book-vote.service';
import { BookOption, BookVoteRound } from '../../../../core/models/book-vote.model';
import { BackendHttpError, RequestTimeoutError } from '../../../../core/interceptors/auth.interceptor';
import { HlmButton } from '../../../../shared/spartan/button/src';

@Component({
  selector: 'app-book-vote-section',
  host: { class: 'block' },
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, TranslateModule, HlmButton],
  templateUrl: './book-vote-section.component.html',
})
export class BookVoteSectionComponent {
  readonly clubId  = input.required<string>();
  readonly isOwner = input(false);
  readonly isMember = input(false);

  private readonly voteService = inject(BookVoteService);
  private readonly translate = inject(TranslateService);

  protected readonly newTitle  = signal('');
  protected readonly newAuthor = signal('');
  protected readonly addError  = signal('');
  protected readonly isActionLoading = signal(false);

  private readonly roundResource = rxResource<BookVoteRound | null, string>({
    params: () => this.clubId(),
    stream: ({ params: clubId }) => this.voteService.getRound$(clubId),
  });

  protected readonly round = computed(() => this.roundResource.value() ?? null);
  protected readonly isLoading = this.roundResource.isLoading;

  protected readonly sortedOptions = computed(() =>
    [...(this.round()?.options ?? [])].sort((a, b) => b.votes - a.votes),
  );

  protected getPercent(option: BookOption): number {
    const total = this.round()?.totalVotes ?? 0;
    return total > 0 ? Math.round((option.votes / total) * 100) : 0;
  }

  /** Localized plural form of "vote(s)" for the given count (uk has one/few/many, en has one/other). */
  protected voteCountLabel(count: number): string {
    const category = new Intl.PluralRules(this.translate.currentLang || 'uk').select(count);
    const key = `BOOK_VOTE.votes_${category}`;
    const label = this.translate.instant(key) as string;
    // Fall back to the "other" form for categories a locale doesn't define (e.g. en has no "few").
    return label === key ? (this.translate.instant('BOOK_VOTE.votes_other') as string) : label;
  }

  protected async createRound(): Promise<void> {
    await this.runAction(() => this.voteService.createRound(this.clubId()));
  }

  protected async addOption(): Promise<void> {
    const title = this.newTitle().trim();
    if (!title) { this.addError.set(this.translate.instant('BOOK_VOTE.title_required_error')); return; }
    const round = this.round();
    if (!round) return;
    this.addError.set('');
    await this.runAction(() => this.voteService.addOption(this.clubId(), round.id, title, this.newAuthor()));
    this.newTitle.set('');
    this.newAuthor.set('');
  }

  protected async removeOption(optionId: string): Promise<void> {
    await this.runAction(() => this.voteService.removeOption(this.clubId(), optionId));
  }

  protected async toggleVote(option: BookOption): Promise<void> {
    if (option.hasVoted) {
      await this.runAction(() => this.voteService.unvote(this.clubId(), option.id));
    } else {
      await this.runAction(() => this.voteService.vote(this.clubId(), option.id));
    }
  }

  protected async closeRound(): Promise<void> {
    const round = this.round();
    if (!round) return;
    await this.runAction(() => this.voteService.closeRound(this.clubId(), round.id));
  }

  protected async newRound(): Promise<void> {
    await this.createRound();
  }

  private async runAction(action: () => Promise<void>): Promise<void> {
    this.isActionLoading.set(true);
    try {
      await action();
      this.roundResource.reload();
    } catch (err) {
      toast.error(this.formatActionError(err, 'Failed to update the vote'));
    } finally {
      this.isActionLoading.set(false);
    }
  }

  private formatActionError(err: unknown, fallback: string): string {
    if (err instanceof RequestTimeoutError) {
      return this.translate.instant('ERRORS.timeout');
    }
    if (err instanceof BackendHttpError) {
      if (err.detail) return err.detail;
      return this.translate.instant(err.translationKey);
    }
    if (err instanceof Error && err.message) return err.message;
    return fallback;
  }
}

@if (isLoading() && !round()) {
<section class="parchment-card px-6 py-5 flex flex-col gap-3">
  <div class="h-4 w-48 rounded bg-gray-200 dark:bg-gray-700 animate-pulse"></div>
  <div class="h-16 rounded-xl bg-gray-200 dark:bg-gray-700 animate-pulse"></div>
</section>
} @else if (round() || isOwner()) {
<section class="parchment-card px-6 py-5 flex flex-col gap-4">

  <!-- ── Header ──────────────────────────────────────────────────── -->
  <div class="flex items-center justify-between">
    <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
      📚 {{ 'BOOK_VOTE.section_title' | translate }}
    </h2>

    @if (isOwner()) {
      @if (round()?.status === 'open') {
        <button hlmBtn variant="outline" size="sm" type="button" [disabled]="isActionLoading()" (click)="closeRound()">
          {{ 'BOOK_VOTE.close_round' | translate }}
        </button>
      } @else if (round()?.status === 'closed') {
        <button hlmBtn size="sm" type="button" [disabled]="isActionLoading()" (click)="newRound()">
          {{ 'BOOK_VOTE.new_round' | translate }}
        </button>
      }
    }
  </div>

  <!-- ── No active round (owner only) ────────────────────────────── -->
  @if (!round()) {
    <div class="flex flex-col items-center gap-3 py-6 text-center">
      <p class="text-sm text-[var(--color-ink-muted)]">
        {{ 'BOOK_VOTE.no_round_prompt' | translate }}
      </p>
      <button hlmBtn size="sm" type="button" [disabled]="isActionLoading()" (click)="createRound()">
        {{ 'BOOK_VOTE.start_round' | translate }}
      </button>
    </div>
  }

  <!-- ── Open round ───────────────────────────────────────────────── -->
  @if (round()?.status === 'open') {

    @if (round()!.options.length === 0) {
      <p class="text-sm text-[var(--color-ink-muted)] text-center py-4">
        {{ 'BOOK_VOTE.no_options_prompt' | translate }}
      </p>
    } @else {
      <ul class="flex flex-col gap-3">
        @for (option of round()!.options; track option.id) {
          <li class="flex flex-col gap-1.5 rounded-xl p-3
                     bg-[var(--color-surface-sunken)]
                     border border-[var(--color-sepia)]">

            <div class="flex items-start justify-between gap-3">
              <div class="min-w-0">
                <p class="font-display font-semibold text-sm text-[var(--color-ink)] leading-snug truncate">
                  {{ option.title }}
                </p>
                @if (option.author) {
                  <p class="text-xs text-[var(--color-ink-muted)] mt-0.5">{{ option.author }}</p>
                }
              </div>

              <div class="flex items-center gap-2 flex-shrink-0">
                @if (isMember() || isOwner()) {
                  <button
                    hlmBtn
                    type="button"
                    size="sm"
                    [attr.variant]="option.hasVoted ? 'default' : 'outline'"
                    [disabled]="isActionLoading()"
                    (click)="toggleVote(option)"
                    class="text-xs"
                  >
                    {{ option.hasVoted ? '✓ ' + ('BOOK_VOTE.voted' | translate) : ('BOOK_VOTE.vote' | translate) }}
                  </button>
                }
                @if (isOwner() && option.votes === 0) {
                  <button
                    type="button"
                    [disabled]="isActionLoading()"
                    (click)="removeOption(option.id)"
                    class="text-[var(--color-ink-muted)] hover:text-red-600 dark:hover:text-red-400
                           transition-colors duration-150 p-1 rounded"
                    [attr.aria-label]="'BOOK_VOTE.remove_option_aria' | translate"
                  >
                    <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                  </button>
                }
              </div>
            </div>

            <!-- Progress bar -->
            <div class="h-1.5 rounded-full bg-[var(--color-surface-raised)] overflow-hidden">
              <div
                class="h-full rounded-full bg-[var(--color-primary-600)] transition-all duration-500"
                [style.width.%]="getPercent(option)"
              ></div>
            </div>
            <p class="text-[11px] text-[var(--color-ink-muted)]">
              {{ option.votes }} {{ voteCountLabel(option.votes) }} · {{ getPercent(option) }}%
            </p>

          </li>
        }
      </ul>
    }

    <!-- Add book form (owner only) -->
    @if (isOwner()) {
      <div class="border-t border-[var(--color-sepia)] pt-4 flex flex-col gap-2">
        <p class="text-xs font-semibold text-[var(--color-ink-muted)] uppercase tracking-wide">{{ 'BOOK_VOTE.add_book_heading' | translate }}</p>
        <div class="flex flex-col sm:flex-row gap-2">
          <input
            type="text"
            [ngModel]="newTitle()"
            (ngModelChange)="newTitle.set($event)"
            [placeholder]="'BOOK_VOTE.title_placeholder' | translate"
            [attr.aria-label]="'BOOK_VOTE.title_aria' | translate"
            class="flex-1 min-w-0 parchment-input rounded-lg px-3 py-2 text-sm"
          />
          <input
            type="text"
            [ngModel]="newAuthor()"
            (ngModelChange)="newAuthor.set($event)"
            [placeholder]="'BOOK_VOTE.author_placeholder' | translate"
            [attr.aria-label]="'BOOK_VOTE.author_aria' | translate"
            class="flex-1 min-w-0 parchment-input rounded-lg px-3 py-2 text-sm"
          />
          <button hlmBtn size="sm" type="button" [disabled]="isActionLoading()" (click)="addOption()" class="flex-shrink-0">
            {{ 'BOOK_VOTE.add_button' | translate }}
          </button>
        </div>
        @if (addError()) {
          <p class="text-xs text-red-600 dark:text-red-400">{{ addError() }}</p>
        }
      </div>
    }
  }

  <!-- ── Closed round: results ────────────────────────────────────── -->
  @if (round()?.status === 'closed') {
    <ul class="flex flex-col gap-3">
      @for (option of sortedOptions(); track option.id) {
        <li
          class="flex flex-col gap-1.5 rounded-xl p-3 border transition-colors"
          [class]="option.id === round()!.winnerId
            ? 'bg-[var(--color-primary-50)] dark:bg-[var(--color-primary-900)]/20 border-[var(--color-primary-400)] ring-1 ring-[var(--color-primary-400)]'
            : 'bg-[var(--color-surface-sunken)] border-[var(--color-sepia)]'"
        >
          <div class="flex items-start justify-between gap-3">
            <div class="min-w-0">
              <p class="font-display font-semibold text-sm text-[var(--color-ink)] leading-snug truncate">
                {{ option.title }}
              </p>
              @if (option.author) {
                <p class="text-xs text-[var(--color-ink-muted)] mt-0.5">{{ option.author }}</p>
              }
            </div>
            @if (option.id === round()!.winnerId) {
              <span class="flex-shrink-0 text-xs font-bold
                           text-[var(--color-primary-700)] dark:text-[#fbbf24]
                           bg-[var(--color-primary-100)] dark:bg-[var(--color-primary-900)]/40
                           border border-[var(--color-primary-300)] dark:border-[var(--color-primary-700)]/60
                           rounded-full px-2.5 py-0.5">
                🏆 {{ 'BOOK_VOTE.winner_badge' | translate }}
              </span>
            }
          </div>

          <div class="h-1.5 rounded-full bg-[var(--color-surface-raised)] overflow-hidden">
            <div
              class="h-full rounded-full transition-all duration-500"
              [class]="option.id === round()!.winnerId
                ? 'bg-[var(--color-primary-500)]'
                : 'bg-[var(--color-ink-muted)]/40'"
              [style.width.%]="getPercent(option)"
            ></div>
          </div>
          <p class="text-[11px] text-[var(--color-ink-muted)]">
            {{ option.votes }} {{ voteCountLabel(option.votes) }} · {{ getPercent(option) }}%
          </p>
        </li>
      }
    </ul>

    @if (round()!.options.length === 0) {
      <p class="text-sm text-[var(--color-ink-muted)] text-center py-4">{{ 'BOOK_VOTE.no_options_closed' | translate }}</p>
    }
  }

</section>
}

// apps/web/src/features/club-detail/book-vote-section.tsx
'use client';
'use no memo';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { AddBookOptionRequest, BookOption, BookVoteRound } from '@book-club/contracts';
import { useTranslations } from 'next-intl';
import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { api } from '@/lib/api';
import { toastError, voteKey } from './use-club-detail';

const ITEM = 'flex flex-col gap-1.5 rounded-xl p-3 border';

function percent(votes: number, total: number): number {
  return total > 0 ? Math.round((votes / total) * 100) : 0;
}

function withVote(round: BookVoteRound, optionId: string, voted: boolean): BookVoteRound {
  const delta = voted ? 1 : -1;
  return {
    ...round,
    totalVotes: Math.max(0, round.totalVotes + delta),
    options: round.options.map((o) => (o.id === optionId ? { ...o, hasVoted: voted, votes: Math.max(0, o.votes + delta) } : o)),
  };
}

export function BookVoteSection({ clubId, isOwner, isMember }: { clubId: string; isOwner: boolean; isMember: boolean }) {
  const t = useTranslations('BOOK_VOTE');
  const tErrors = useTranslations('ERRORS');
  const queryClient = useQueryClient();
  const key = voteKey(clubId);
  const [title, setTitle] = useState('');
  const [author, setAuthor] = useState('');
  const [addError, setAddError] = useState('');

  const query = useQuery({ queryKey: key, queryFn: () => api.bookVote.currentRound(clubId), refetchOnWindowFocus: false });
  const round = query.data ?? null;

  const invalidate = () => queryClient.invalidateQueries({ queryKey: key });
  const onError = (err: unknown) => toastError(err, tErrors);

  const run = useMutation({
    mutationFn: (action: () => Promise<unknown>) => action(),
    onSuccess: invalidate,
    onError,
  });

  const toggle = useMutation({
    mutationFn: (option: BookOption) => (option.hasVoted ? api.bookVote.unvote(clubId, option.id) : api.bookVote.vote(clubId, option.id)),
    onMutate: async (option) => {
      await queryClient.cancelQueries({ queryKey: key });
      const previous = queryClient.getQueryData<BookVoteRound | null>(key);
      if (previous) queryClient.setQueryData(key, withVote(previous, option.id, !option.hasVoted));
      return { previous };
    },
    onError: (err, _option, context) => {
      queryClient.setQueryData(key, context?.previous ?? null);
      onError(err);
    },
    onSettled: invalidate,
  });

  const busy = run.isPending || toggle.isPending;

  const addOption = (event: FormEvent) => {
    event.preventDefault();
    const trimmed = title.trim();
    if (!trimmed) return setAddError(t('title_required_error'));
    if (!round) return;
    setAddError('');
    const body: AddBookOptionRequest = { title: trimmed, author };
    run.mutate(() => api.bookVote.addOption(clubId, round.id, body), {
      onSuccess: () => {
        setTitle('');
        setAuthor('');
      },
    });
  };

  if (query.isPending) {
    return (
      <section className="parchment-card px-6 py-5 flex flex-col gap-3" aria-busy="true">
        <div className="h-4 w-48 rounded bg-gray-200 dark:bg-gray-700 animate-pulse" />
        <div className="h-16 rounded-xl bg-gray-200 dark:bg-gray-700 animate-pulse" />
      </section>
    );
  }
  if (!round && !isOwner) return null;

  const total = round?.totalVotes ?? 0;
  const newRound = () => run.mutate(() => api.bookVote.createRound(clubId));

  const meta = (option: BookOption) => (
    <p className="text-[11px] text-[var(--color-ink-muted)]">
      {option.votes} {t('votes', { count: option.votes })} · {percent(option.votes, total)}%
    </p>
  );

  return (
    <section className="parchment-card px-6 py-5 flex flex-col gap-4" aria-labelledby="book-vote-title">
      <div className="flex items-center justify-between">
        <h2 id="book-vote-title" className="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide">
          📚 {t('section_title')}
        </h2>
        {isOwner && round?.status === 'open' && (
          <Button type="button" variant="outline" size="sm" disabled={busy} onClick={() => run.mutate(() => api.bookVote.closeRound(clubId, round.id))}>
            {t('close_round')}
          </Button>
        )}
        {isOwner && round?.status === 'closed' && (
          <Button type="button" size="sm" disabled={busy} onClick={newRound}>
            {t('new_round')}
          </Button>
        )}
      </div>

      {!round && (
        <div className="flex flex-col items-center gap-3 py-6 text-center">
          <p className="text-sm text-[var(--color-ink-muted)]">{t('no_round_prompt')}</p>
          <Button type="button" size="sm" disabled={busy} onClick={newRound}>
            {t('start_round')}
          </Button>
        </div>
      )}

      {round?.status === 'open' && (
        <>
          {round.options.length === 0 ? (
            <p className="text-sm text-[var(--color-ink-muted)] text-center py-4">{t('no_options_prompt')}</p>
          ) : (
            <ul className="flex flex-col gap-3">
              {round.options.map((option) => (
                <li key={option.id} className={`${ITEM} bg-[var(--color-surface-sunken)] border-[var(--color-sepia)]`}>
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="font-display font-semibold text-sm text-[var(--color-ink)] leading-snug truncate">{option.title}</p>
                      {option.author && <p className="text-xs text-[var(--color-ink-muted)] mt-0.5">{option.author}</p>}
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      {(isMember || isOwner) && (
                        <Button
                          type="button"
                          size="sm"
                          variant={option.hasVoted ? 'default' : 'outline'}
                          aria-pressed={option.hasVoted}
                          disabled={busy}
                          onClick={() => toggle.mutate(option)}
                          className="text-xs"
                        >
                          {option.hasVoted ? `✓ ${t('voted')}` : t('vote')}
                        </Button>
                      )}
                      {isOwner && option.votes === 0 && (
                        <button
                          type="button"
                          disabled={busy}
                          onClick={() => run.mutate(() => api.bookVote.removeOption(clubId, option.id))}
                          className="text-[var(--color-ink-muted)] hover:text-red-600 dark:hover:text-red-400 transition-colors duration-150 p-1 rounded focus-visible:outline-2"
                          aria-label={t('remove_option_aria')}
                        >
                          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                          </svg>
                        </button>
                      )}
                    </div>
                  </div>
                  <div className="h-1.5 rounded-full bg-[var(--color-surface-raised)] overflow-hidden">
                    <div className="h-full rounded-full bg-[var(--color-primary-600)] transition-all duration-500" style={{ width: `${percent(option.votes, total)}%` }} />
                  </div>
                  {meta(option)}
                </li>
              ))}
            </ul>
          )}

          {isOwner && (
            <form onSubmit={addOption} className="border-t border-[var(--color-sepia)] pt-4 flex flex-col gap-2" noValidate>
              <p className="text-xs font-semibold text-[var(--color-ink-muted)] uppercase tracking-wide">{t('add_book_heading')}</p>
              <div className="flex flex-col sm:flex-row gap-2">
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder={t('title_placeholder')}
                  aria-label={t('title_aria')}
                  aria-invalid={addError ? true : undefined}
                  aria-describedby={addError ? 'book-vote-add-error' : undefined}
                  className="flex-1 min-w-0 parchment-input rounded-lg px-3 py-2 text-sm"
                />
                <input
                  type="text"
                  value={author}
                  onChange={(e) => setAuthor(e.target.value)}
                  placeholder={t('author_placeholder')}
                  aria-label={t('author_aria')}
                  className="flex-1 min-w-0 parchment-input rounded-lg px-3 py-2 text-sm"
                />
                <Button type="submit" size="sm" disabled={busy} className="flex-shrink-0">
                  {t('add_button')}
                </Button>
              </div>
              {addError && (
                <p id="book-vote-add-error" className="text-xs text-red-600 dark:text-red-400">
                  {addError}
                </p>
              )}
            </form>
          )}
        </>
      )}

      {round?.status === 'closed' && (
        <>
          <ul className="flex flex-col gap-3">
            {[...round.options]
              .sort((a, b) => b.votes - a.votes)
              .map((option) => {
                const won = option.id === round.winnerId;
                return (
                  <li
                    key={option.id}
                    className={`${ITEM} transition-colors ${
                      won
                        ? 'bg-[var(--color-primary-50)] dark:bg-[var(--color-primary-900)]/20 border-[var(--color-primary-400)] ring-1 ring-[var(--color-primary-400)]'
                        : 'bg-[var(--color-surface-sunken)] border-[var(--color-sepia)]'
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="min-w-0">
                        <p className="font-display font-semibold text-sm text-[var(--color-ink)] leading-snug truncate">{option.title}</p>
                        {option.author && <p className="text-xs text-[var(--color-ink-muted)] mt-0.5">{option.author}</p>}
                      </div>
                      {won && (
                        <span className="flex-shrink-0 text-xs font-bold text-[var(--color-primary-700)] dark:text-[#fbbf24] bg-[var(--color-primary-100)] dark:bg-[var(--color-primary-900)]/40 border border-[var(--color-primary-300)] dark:border-[var(--color-primary-700)]/60 rounded-full px-2.5 py-0.5">
                          🏆 {t('winner_badge')}
                        </span>
                      )}
                    </div>
                    <div className="h-1.5 rounded-full bg-[var(--color-surface-raised)] overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all duration-500 ${won ? 'bg-[var(--color-primary-500)]' : 'bg-[var(--color-ink-muted)]/40'}`}
                        style={{ width: `${percent(option.votes, total)}%` }}
                      />
                    </div>
                    {meta(option)}
                  </li>
                );
              })}
          </ul>
          {round.options.length === 0 && <p className="text-sm text-[var(--color-ink-muted)] text-center py-4">{t('no_options_closed')}</p>}
        </>
      )}
    </section>
  );
}
