// src/app/shared/components/qr-code/qr-code.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  effect,
  input,
  viewChild,
} from '@angular/core';
import { environment } from '../../../../environments/environment';
import { HlmCard } from '../../spartan/card/src';

@Component({
  selector: 'app-qr-code',
  standalone: true,
  imports: [HlmCard],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div hlmCard class="flex items-center justify-center p-6 w-fit gap-0 py-6">
      <canvas
        #canvas
        [style.width.px]="size()"
        [style.height.px]="size()"
        class="rounded-lg"
        [attr.aria-label]="'QR code'"
        role="img"
      ></canvas>
    </div>
  `,
})
export class QrCodeComponent {
  readonly value = input.required<string>();
  readonly size = input<number>(200);

  private readonly canvasRef =
    viewChild.required<ElementRef<HTMLCanvasElement>>('canvas');

  constructor() {
    effect(() => {
      const val = this.value();
      const sz = this.size();
      const canvas = this.canvasRef().nativeElement;
      if (!val || !canvas) return;
      void import('qrcode').then((QRCode) => {
        QRCode.toCanvas(canvas, val, { width: sz, margin: 2 }, (err) => {
          if (err && !environment.production) console.error('QR generation error:', err);
        });
      });
    });
  }
}

// apps/web/src/features/club-detail/qr-code.tsx
'use client';

import { useEffect, useRef } from 'react';

/** Renders `value` as a QR code; the generator is fetched only when a code is first shown. */
export function QrCode({ value, size = 200 }: { value: string; size?: number }) {
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    let cancelled = false;
    void import('qrcode').then(({ default: qr }) => {
      const el = canvas.current;
      if (cancelled || !el || !value) return;
      qr.toCanvas(el, value, { width: size, margin: 2 }).catch(() => undefined);
    });
    return () => {
      cancelled = true;
    };
  }, [value, size]);

  return (
    <div className="parchment-card flex items-center justify-center p-6 w-fit">
      <canvas ref={canvas} role="img" aria-label="QR code" style={{ width: size, height: size }} className="rounded-lg" />
    </div>
  );
}
