// src/app/layout/header/header.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  inject,
  computed,
} from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { map, startWith } from 'rxjs';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { AuthService } from '../../core/auth/auth.service';
import { HlmDropdownMenuImports } from '../../shared/spartan/dropdown-menu/src';
import { HlmSheetImports } from '../../shared/spartan/sheet/src';
import { HlmButton } from '../../shared/spartan/button/src';

@Component({
  selector: 'app-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive, TranslateModule, ...HlmDropdownMenuImports, ...HlmSheetImports, HlmButton],
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  private readonly auth = inject(AuthService);
  private readonly translate = inject(TranslateService);

  readonly isAuthenticated = this.auth.isAuthenticated;
  readonly currentUser = this.auth.currentUser;

  readonly currentLang = toSignal(
    this.translate.onLangChange.pipe(
      map(e => e.lang),
      startWith(this.translate.currentLang ?? 'uk'),
    ),
    { initialValue: 'uk' },
  );

  readonly userInitials = computed(() => {
    const name = this.currentUser()?.displayName ?? '';
    return (
      name
        .split(' ')
        .slice(0, 2)
        .map(w => w[0]?.toUpperCase() ?? '')
        .join('') || '?'
    );
  });

  switchLang(): void {
    const next = this.currentLang() === 'uk' ? 'en' : 'uk';
    this.translate.use(next).subscribe();
  }

  async signOut(): Promise<void> {
    await this.auth.signOut();
  }
}

<header
  class="sticky top-0 z-50
         bg-[var(--color-surface)]/90 dark:bg-[var(--color-surface)]/95
         backdrop-blur-[10px]
         border-b border-[var(--color-sepia)]
         shadow-[0_2px_12px_rgba(92,45,10,0.10)] dark:shadow-[0_2px_16px_rgba(0,0,0,0.40)]"
  role="banner"
>
  <div class="page-max-w px-6">
    <div class="flex items-center justify-between h-16">

      <!-- ── Logo ──────────────────────────────────────────────────── -->
      <a
        routerLink="/"
        class="font-fantasy text-xl font-bold tracking-widest
               text-[var(--color-primary-600)] dark:text-[#fbbf24]
               hover:text-[var(--color-primary-500)] dark:hover:text-[#fcd34d]
               transition-colors duration-200
               focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2 rounded"
        aria-label="BookClub home"
      >
        BookClub
      </a>

      <!-- ── Desktop Nav ────────────────────────────────────────────── -->
      <nav class="hidden md:flex items-center gap-1" aria-label="Main navigation">
        <a
          routerLink="/events"
          data-testid="nav-events"
          routerLinkActive="text-[var(--color-primary-600)] dark:text-[#fbbf24] bg-[var(--color-primary-100)]/80 dark:bg-[var(--color-primary-900)]/30 font-semibold"
          [routerLinkActiveOptions]="{exact: true}"
          class="px-4 py-2 rounded-lg text-sm font-medium
                 text-[var(--color-ink-muted)]
                 hover:text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                 transition-all duration-200
                 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
        >
          {{ 'NAV.events' | translate }}
        </a>
        @if (isAuthenticated()) {
          <a
            routerLink="/clubs"
            data-testid="nav-clubs"
            routerLinkActive="text-[var(--color-primary-600)] dark:text-[#fbbf24] bg-[var(--color-primary-100)]/80 dark:bg-[var(--color-primary-900)]/30 font-semibold"
            [routerLinkActiveOptions]="{exact: true}"
            class="px-4 py-2 rounded-lg text-sm font-medium
                   text-[var(--color-ink-muted)]
                   hover:text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                   transition-all duration-200
                   focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
          >
            {{ 'NAV.clubs' | translate }}
          </a>
          @if (currentUser()?.role === 'organizer') {
            <a
              routerLink="/manage"
              data-testid="nav-manage"
              routerLinkActive="text-[var(--color-primary-600)] dark:text-[#fbbf24] bg-[var(--color-primary-100)]/80 dark:bg-[var(--color-primary-900)]/30 font-semibold"
              [routerLinkActiveOptions]="{exact: true}"
              class="px-4 py-2 rounded-lg text-sm font-medium
                     text-[var(--color-ink-muted)]
                     hover:text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                     transition-all duration-200
                     focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
            >
              {{ 'NAV.manage' | translate }}
            </a>
          }
        }
      </nav>

      <!-- ── Desktop Right ─────────────────────────────────────────── -->
      <div class="hidden md:flex items-center gap-1">

        <!-- Theme Toggle -->
        <button
          hlmBtn
          variant="ghost"
          size="icon"
          type="button"
          data-testid="theme-toggle"
          (click)="themeService.toggle()"
          [attr.aria-pressed]="themeService.isDark()"
          [attr.aria-label]="themeService.isDark()
            ? ('NAV.theme_toggle_light' | translate)
            : ('NAV.theme_toggle_dark'  | translate)"
          [attr.title]="themeService.isDark()
            ? ('NAV.theme_toggle_light' | translate)
            : ('NAV.theme_toggle_dark'  | translate)"
        >
          @if (themeService.isDark()) {
            <ng-icon hlm name="lucideSun"  size="sm" />
          } @else {
            <ng-icon hlm name="lucideMoon" size="sm" />
          }
        </button>

        <!-- Language switcher -->
        <button
          hlmBtn
          variant="ghost"
          size="sm"
          type="button"
          (click)="switchLang()"
          [attr.aria-label]="currentLang() === 'uk' ? 'Switch to English' : 'Перейти на українську'"
        >
          {{ currentLang() === 'uk' ? 'EN' : 'UK' }}
        </button>

        @if (isAuthenticated()) {
          <!-- User avatar + dropdown -->
          <div class="relative">
            <button
              type="button"
              (click)="showUserMenu.set(!showUserMenu())"
              class="flex items-center gap-2 rounded-full p-0.5 transition-all duration-200
                     focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
              aria-haspopup="menu"
              [attr.aria-expanded]="showUserMenu()"
              [attr.aria-label]="'User menu for ' + (currentUser()?.displayName ?? 'User')"
            >
              <div
                class="h-9 w-9 rounded-full avatar-gradient
                       flex items-center justify-center text-white text-sm font-semibold select-none"
                aria-hidden="true"
              >
                {{ userInitials() }}
              </div>
            </button>

            @if (showUserMenu()) {
              <div
                class="absolute right-0 mt-2 w-48 rounded-md border border-[var(--color-sepia)]
                       bg-[var(--color-surface)] shadow-lg z-50 py-1"
                role="menu"
              >
                <div class="px-3 py-2 text-sm font-semibold text-[var(--color-ink)]">
                  {{ currentUser()?.displayName }}
                </div>
                <hr class="border-[var(--color-sepia)] my-1" />
                <a
                  [routerLink]="['/chats']"
                  (click)="showUserMenu.set(false)"
                  class="block px-3 py-2 text-sm text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)] transition-colors"
                  role="menuitem"
                >
                  {{ 'NAV.chats' | translate }}
                </a>
                <a
                  [routerLink]="['/profile']"
                  (click)="showUserMenu.set(false)"
                  class="block px-3 py-2 text-sm text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)] transition-colors"
                  role="menuitem"
                >
                  {{ 'NAV.profile' | translate }}
                </a>
                <hr class="border-[var(--color-sepia)] my-1" />
                <button
                  type="button"
                  data-testid="logout"
                  (click)="signOut()"
                  class="w-full text-left px-3 py-2 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
                  role="menuitem"
                >
                  {{ 'NAV.logout' | translate }}
                </button>
              </div>
            }
          </div>

        } @else {
          <a hlmBtn variant="outline" size="sm" routerLink="/login">
            {{ 'NAV.login' | translate }}
          </a>
          <a hlmBtn size="sm" routerLink="/register"
             class="bg-gradient-fantasy text-white border-0 hover:opacity-90">
            {{ 'NAV.join_free' | translate }}
          </a>
        }
      </div>

      <!-- ── Hamburger (mobile) — Spartan Sheet ─────────────────────── -->
      <hlm-sheet class="md:hidden">
        <button
          hlmSheetTrigger
          type="button"
          class="p-2 rounded-lg text-[var(--color-ink-muted)]
                 hover:bg-[var(--color-surface-raised)] transition-all duration-200
                 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2"
          aria-label="Toggle navigation menu"
        >
          <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>

        <ng-template hlmSheetPortal>
          <hlm-sheet-content>
            <hlm-sheet-header>
              <h2 hlmSheetTitle
                  class="font-fantasy font-bold tracking-widest text-[var(--color-primary-600)] dark:text-[#fbbf24]">
                BookClub
              </h2>
            </hlm-sheet-header>

            <nav class="flex flex-col gap-1 px-4 py-2" aria-label="Mobile navigation">
              <button hlmSheetClose [routerLink]="['/events']"
                      class="flex items-center px-4 py-2.5 rounded-lg text-sm font-medium
                             text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                             transition-all duration-200 w-full text-left">
                {{ 'NAV.events' | translate }}
              </button>
              @if (isAuthenticated()) {
                <button hlmSheetClose [routerLink]="['/clubs']"
                        class="flex items-center px-4 py-2.5 rounded-lg text-sm font-medium
                               text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                               transition-all duration-200 w-full text-left">
                  {{ 'NAV.clubs' | translate }}
                </button>
                @if (currentUser()?.role === 'organizer') {
                  <button hlmSheetClose [routerLink]="['/manage']"
                          data-testid="nav-manage-mobile"
                          class="flex items-center px-4 py-2.5 rounded-lg text-sm font-medium
                                 text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                                 transition-all duration-200 w-full text-left">
                    {{ 'NAV.manage' | translate }}
                  </button>
                }
              }

              <!-- Theme Toggle (mobile) -->
              <button
                type="button"
                data-testid="theme-toggle"
                (click)="themeService.toggle()"
                [attr.aria-pressed]="themeService.isDark()"
                class="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium
                       text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                       transition-all duration-200 w-full text-left"
                [attr.aria-label]="themeService.isDark()
                  ? ('NAV.theme_toggle_light' | translate)
                  : ('NAV.theme_toggle_dark'  | translate)"
              >
                @if (themeService.isDark()) {
                  <ng-icon hlm name="lucideSun"  size="sm" />
                  <span>{{ 'NAV.theme_toggle_light' | translate }}</span>
                } @else {
                  <ng-icon hlm name="lucideMoon" size="sm" />
                  <span>{{ 'NAV.theme_toggle_dark' | translate }}</span>
                }
              </button>

              <!-- Language (mobile) -->
              <button
                type="button"
                (click)="switchLang()"
                class="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium
                       text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                       transition-all duration-200 w-full text-left"
                [attr.aria-label]="currentLang() === 'uk' ? 'Switch to English' : 'Перейти на українську'"
              >
                <span>{{ currentLang() === 'uk' ? '🇬🇧 EN' : '🇺🇦 UK' }}</span>
              </button>

              <div class="pt-2 mt-2 border-t border-[var(--color-sepia)] flex flex-col gap-1">
                @if (isAuthenticated()) {
                  <div class="px-4 py-2">
                    <p class="text-xs font-semibold text-[var(--color-ink-muted)] uppercase tracking-wide">
                      {{ 'NAV.signed_in_as' | translate }}
                    </p>
                    <p class="text-sm font-medium text-[var(--color-ink)] mt-0.5">
                      {{ currentUser()?.displayName }}
                    </p>
                  </div>
                  <button hlmSheetClose [routerLink]="['/profile']"
                          class="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium
                                 text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                                 transition-all duration-200 w-full text-left">
                    {{ 'NAV.profile' | translate }}
                  </button>
                  <button hlmSheetClose type="button" data-testid="logout" (click)="signOut()"
                          class="w-full flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-medium
                                 text-red-700 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20
                                 transition-all duration-200">
                    {{ 'NAV.logout' | translate }}
                  </button>
                } @else {
                  <button hlmSheetClose [routerLink]="['/login']"
                          class="flex items-center px-4 py-2.5 rounded-lg text-sm font-medium
                                 text-[var(--color-ink)] hover:bg-[var(--color-surface-raised)]
                                 transition-all duration-200 w-full text-left">
                    {{ 'NAV.login' | translate }}
                  </button>
                  <button hlmSheetClose [routerLink]="['/register']"
                          class="flex items-center px-4 py-2.5 rounded-lg text-sm font-medium
                                 bg-gradient-fantasy text-white hover:opacity-90
                                 transition-all duration-200 w-full text-left">
                    {{ 'NAV.join_free' | translate }}
                  </button>
                }
              </div>
            </nav>
          </hlm-sheet-content>
        </ng-template>
      </hlm-sheet>

    </div>
  </div>
</header>

// apps/web/src/components/layout/header.tsx
'use client';

import { useTranslations } from 'next-intl';
import { AppLink } from '@/components/app-link';
import { Button } from '@/components/ui/button';
import { useSession } from '@/features/clubs/use-session';
import { api } from '@/lib/api';
import { hardNavigate } from '@/lib/navigate';
import { LocaleSwitch, useLocaleSwitch } from './locale-switch';
import { MobileNav } from './mobile-nav';
import { NavLinks } from './nav-links';
import { ThemeSwitch, useTheme } from './theme-switch';
import { UserMenu } from './user-menu';

export function Header({ initialDark }: { initialDark: boolean }) {
  const t = useTranslations('NAV');
  const { user, isPending } = useSession();
  const { isDark, toggle } = useTheme(initialDark);
  const { locale, switchLocale } = useLocaleSwitch();

  const signOut = async () => {
    try {
      await api.auth.logout();
    } catch {
      // logout must complete even if the request fails
    }
    hardNavigate('/login');
  };

  return (
    <header
      className="sticky top-0 z-50 bg-[var(--color-surface)]/90 dark:bg-[var(--color-surface)]/95 backdrop-blur-[10px] border-b border-[var(--color-sepia)] shadow-[0_2px_12px_rgba(92,45,10,0.10)] dark:shadow-[0_2px_16px_rgba(0,0,0,0.40)]"
      role="banner"
    >
      <div className="page-max-w px-6">
        <div className="flex items-center justify-between h-16">
          <AppLink
            href="/"
            className="font-fantasy text-xl font-bold tracking-widest text-[var(--color-primary-600)] dark:text-[#fbbf24] hover:text-[var(--color-primary-500)] dark:hover:text-[#fcd34d] transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)] focus:ring-offset-2 rounded"
            aria-label="BookClub home"
          >
            BookClub
          </AppLink>

          <NavLinks isAuthenticated={user !== null} />

          <div className="hidden md:flex items-center gap-1">
            <ThemeSwitch isDark={isDark} toggle={toggle} />
            <LocaleSwitch locale={locale} switchLocale={switchLocale} />
            {user ? (
              <UserMenu displayName={user.displayName} onSignOut={signOut} />
            ) : (
              // reserves the auth area's space so a signed-in user's avatar does not shift the header when the session resolves
              <div className={isPending ? 'invisible flex items-center gap-1' : 'flex items-center gap-1'} aria-hidden={isPending || undefined}>
                <Button asChild variant="outline" size="sm">
                  <AppLink href="/login" tabIndex={isPending ? -1 : undefined}>
                    {t('login')}
                  </AppLink>
                </Button>
                <Button asChild size="sm" className="bg-gradient-fantasy! text-white border-0 hover:opacity-90">
                  <AppLink href="/register" tabIndex={isPending ? -1 : undefined}>
                    {t('join_free')}
                  </AppLink>
                </Button>
              </div>
            )}
          </div>

          <MobileNav
            isAuthenticated={user !== null}
            displayName={user?.displayName ?? null}
            isDark={isDark}
            locale={locale}
            onToggleTheme={toggle}
            onSwitchLocale={switchLocale}
            onSignOut={signOut}
          />
        </div>
      </div>
    </header>
  );
}
