// src/app/features/privacy/privacy.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-privacy',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink],
  template: `
    <div class="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4">
      <div class="max-w-3xl mx-auto">
        <a routerLink="/clubs" class="text-sm text-primary-600 dark:text-primary-400 hover:underline">← Назад</a>

        <h1 class="text-3xl font-bold text-gray-900 dark:text-white mt-6 mb-2">Політика конфіденційності</h1>
        <p class="text-sm text-gray-500 dark:text-gray-400 mb-8">Останнє оновлення: травень 2026 р.</p>

        <div class="space-y-8 text-gray-700 dark:text-gray-300 leading-relaxed">

          <section>
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Які дані ми збираємо</h2>
            <p>Під час реєстрації ми збираємо ваше ім'я користувача та адресу електронної пошти. При використанні сервісу ми можемо зберігати інформацію про вашу участь у книжкових клубах, результати квізів та налаштування профілю (соціальні мережі, роль).</p>
          </section>

          <section>
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Як ми використовуємо ваші дані</h2>
            <ul class="list-disc pl-5 space-y-1">
              <li>Надання та підтримка функцій платформи (клуби, події, квізи).</li>
              <li>Персоналізація вашого досвіду: відображення ваших клубів та статистики.</li>
              <li>Зв'язок з вами у разі важливих змін у сервісі.</li>
            </ul>
            <p class="mt-3">Ми не продаємо та не передаємо ваші персональні дані третім сторонам у комерційних цілях.</p>
          </section>

          <section>
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. Зберігання даних</h2>
            <p>Дані зберігаються на захищених серверах. Ваш пароль зберігається у хешованому вигляді — ми не маємо доступу до вашого пароля у відкритому вигляді. Токени доступу зберігаються лише в пам'яті браузера і не записуються до локального сховища.</p>
          </section>

          <section>
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Ваші права (GDPR)</h2>
            <ul class="list-disc pl-5 space-y-1">
              <li><strong>Доступ:</strong> ви можете запросити копію своїх даних.</li>
              <li><strong>Виправлення:</strong> ви можете оновити ім'я та соціальні мережі в налаштуваннях профілю.</li>
              <li><strong>Видалення:</strong> ви можете надіслати запит на видалення акаунту та всіх пов'язаних даних.</li>
              <li><strong>Заперечення:</strong> ви маєте право заперечувати проти певних видів обробки даних.</li>
            </ul>
          </section>

          <section>
            <h2 class="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Контакти</h2>
            <p>З питань конфіденційності звертайтеся: <a href="mailto:privacy&#64;bookclub.ua" class="text-primary-600 dark:text-primary-400 hover:underline">privacy&#64;bookclub.ua</a></p>
          </section>

        </div>
      </div>
    </div>
  `,
})
export class PrivacyComponent {}

// apps/web/src/app/(public)/privacy/page.tsx
import { AppLink } from '@/components/app-link';
import { pageMetadata } from '@/lib/page-metadata';

export const generateMetadata = () => pageMetadata('TITLES.privacy', '/privacy');

export default function PrivacyPage() {
  return (
    <main lang="uk" className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4">
      <div className="max-w-3xl mx-auto">
        <AppLink href="/events" className="text-sm text-primary-700 dark:text-primary-300 hover:underline cursor-pointer">
          ← Назад
        </AppLink>

        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mt-6 mb-2">Політика конфіденційності</h1>
        <p className="text-sm text-gray-600 dark:text-gray-300 mb-8">Останнє оновлення: травень 2026 р.</p>

        <div className="space-y-8 text-gray-700 dark:text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">1. Які дані ми збираємо</h2>
            <p>
              Під час реєстрації ми збираємо ваше ім&apos;я користувача та адресу електронної пошти. При використанні сервісу ми
              можемо зберігати інформацію про вашу участь у книжкових клубах, результати квізів та налаштування профілю (соціальні
              мережі, роль).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2. Як ми використовуємо ваші дані</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Надання та підтримка функцій платформи (клуби, події, квізи).</li>
              <li>Персоналізація вашого досвіду: відображення ваших клубів та статистики.</li>
              <li>Зв&apos;язок з вами у разі важливих змін у сервісі.</li>
            </ul>
            <p className="mt-3">Ми не продаємо та не передаємо ваші персональні дані третім сторонам у комерційних цілях.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">3. Зберігання даних</h2>
            <p>
              Дані зберігаються на захищених серверах. Ваш пароль зберігається у хешованому вигляді — ми не маємо доступу до вашого
              пароля у відкритому вигляді. Токени доступу зберігаються лише в пам&apos;яті браузера і не записуються до локального
              сховища.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">4. Ваші права (GDPR)</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>
                <strong>Доступ:</strong> ви можете запросити копію своїх даних.
              </li>
              <li>
                <strong>Виправлення:</strong> ви можете оновити ім&apos;я та соціальні мережі в налаштуваннях профілю.
              </li>
              <li>
                <strong>Видалення:</strong> ви можете надіслати запит на видалення акаунту та всіх пов&apos;язаних даних.
              </li>
              <li>
                <strong>Заперечення:</strong> ви маєте право заперечувати проти певних видів обробки даних.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">5. Контакти</h2>
            <p>
              З питань конфіденційності звертайтеся:{' '}
              <a href="mailto:privacy@bookclub.ua" className="text-primary-700 dark:text-primary-300 underline">
                privacy@bookclub.ua
              </a>
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
